#
# This file is generated by ModusToolbox during the 'make getlibs' operation
# Any edits to this file will be lost the next time the library manager is run or
# the next time 'make getlibs' is run.
#
# List of local libraries


# Path to the current BSP
SEARCH_TARGET_APP_KIT_PSE84_HMI=../bsps/TARGET_APP_KIT_PSE84_HMI

# The search paths for the included middleware
SEARCH_audio-codec-tlv320dac3100=../../mtb_shared/audio-codec-tlv320dac3100/latest-v1.X
SEARCH_audio-front-end=../../mtb_shared/audio-front-end/latest-v1.X
SEARCH_audio-voice-core=../../mtb_shared/audio-voice-core/latest-v1.X
SEARCH_block-storage=../../mtb_shared/block-storage/latest-v1.X
SEARCH_display-dsi-waveshare-4-3-lcd=../../mtb_shared/display-dsi-waveshare-4-3-lcd/latest-v1.X
SEARCH_emeeprom=../../mtb_shared/emeeprom/latest-v2.X
SEARCH_emusb-device=../../mtb_shared/emusb-device/latest-v2.X
SEARCH_freertos=../../mtb_shared/freertos/latest-v10.X
SEARCH_lvgl=../../mtb_shared/lvgl/v9.2.0
SEARCH_ml-middleware=../../mtb_shared/ml-middleware/latest-v3.X
SEARCH_ml-tflite-micro=../../mtb_shared/ml-tflite-micro/latest-v3.X
SEARCH_retarget-io=../../mtb_shared/retarget-io/latest-v1.X
SEARCH_touch-ctp-ft5406=../../mtb_shared/touch-ctp-ft5406/latest-v1.X
SEARCH_voice-assistant=../../mtb_shared/voice-assistant/latest-v1.X
SEARCH_abstraction-rtos=../../mtb_shared/abstraction-rtos/release-v1.12.0
SEARCH_async-transfer=../../mtb_shared/async-transfer/release-v1.1.0
SEARCH_bt-fw-mur-cyw55513=../../mtb_shared/bt-fw-mur-cyw55513/release-v1.0.0
SEARCH_clib-support=../../mtb_shared/clib-support/release-v1.8.0
SEARCH_cmsis=../../mtb_shared/cmsis/release-v6.1.0
SEARCH_connectivity-utilities=../../mtb_shared/connectivity-utilities/release-v4.5.2
SEARCH_core-lib=../../mtb_shared/core-lib/release-v1.6.0
SEARCH_core-make=../../mtb_shared/core-make/release-v3.7.0
SEARCH_mtb-dsl-pse8xxgp=../../mtb_shared/mtb-dsl-pse8xxgp/release-v1.1.1
SEARCH_mtb-ipc=../../mtb_shared/mtb-ipc/release-v1.1.0
SEARCH_mtb-srf=../../mtb_shared/mtb-srf/release-v1.1.0
SEARCH_se-rt-services-utils=../../mtb_shared/se-rt-services-utils/release-v1.2.0
SEARCH_speech-onset-detection=../../mtb_shared/speech-onset-detection/release-v1.0.1

# Search libraries added to build
SEARCH_MTB_MK+=$(SEARCH_audio-codec-tlv320dac3100)
SEARCH_MTB_MK+=$(SEARCH_audio-front-end)
SEARCH_MTB_MK+=$(SEARCH_audio-voice-core)
SEARCH_MTB_MK+=$(SEARCH_block-storage)
SEARCH_MTB_MK+=$(SEARCH_display-dsi-waveshare-4-3-lcd)
SEARCH_MTB_MK+=$(SEARCH_emeeprom)
SEARCH_MTB_MK+=$(SEARCH_emusb-device)
SEARCH_MTB_MK+=$(SEARCH_freertos)
SEARCH_MTB_MK+=$(SEARCH_lvgl)
SEARCH_MTB_MK+=$(SEARCH_ml-middleware)
SEARCH_MTB_MK+=$(SEARCH_ml-tflite-micro)
SEARCH_MTB_MK+=$(SEARCH_retarget-io)
SEARCH_MTB_MK+=$(SEARCH_touch-ctp-ft5406)
SEARCH_MTB_MK+=$(SEARCH_voice-assistant)
SEARCH_MTB_MK+=$(SEARCH_abstraction-rtos)
SEARCH_MTB_MK+=$(SEARCH_async-transfer)
SEARCH_MTB_MK+=$(SEARCH_bt-fw-mur-cyw55513)
SEARCH_MTB_MK+=$(SEARCH_clib-support)
SEARCH_MTB_MK+=$(SEARCH_cmsis)
SEARCH_MTB_MK+=$(SEARCH_connectivity-utilities)
SEARCH_MTB_MK+=$(SEARCH_core-lib)
SEARCH_MTB_MK+=$(SEARCH_core-make)
SEARCH_MTB_MK+=$(SEARCH_mtb-dsl-pse8xxgp)
SEARCH_MTB_MK+=$(SEARCH_mtb-ipc)
SEARCH_MTB_MK+=$(SEARCH_mtb-srf)
SEARCH_MTB_MK+=$(SEARCH_se-rt-services-utils)
SEARCH_MTB_MK+=$(SEARCH_speech-onset-detection)

-include $(CY_INTERNAL_APP_PATH)/importedbsp.mk
COMPONENTS += MW_AUDIO_CODEC_TLV320DAC3100
COMPONENTS += MW_AUDIO_FRONT_END
COMPONENTS += MW_AUDIO_VOICE_CORE
COMPONENTS += MW_BLOCK_STORAGE
COMPONENTS += MW_DISPLAY_DSI_WAVESHARE_4_3_LCD
COMPONENTS += MW_EMEEPROM
COMPONENTS += MW_EMUSB_DEVICE
COMPONENTS += MW_FREERTOS
COMPONENTS += MW_LVGL
COMPONENTS += MW_ML_MIDDLEWARE
COMPONENTS += MW_ML_TFLITE_MICRO
COMPONENTS += MW_RETARGET_IO
COMPONENTS += MW_TOUCH_CTP_FT5406
COMPONENTS += MW_VOICE_ASSISTANT
COMPONENTS += MW_ABSTRACTION_RTOS
COMPONENTS += MW_ASYNC_TRANSFER
COMPONENTS += MW_BT_FW_MUR_CYW55513
COMPONENTS += MW_CLIB_SUPPORT
COMPONENTS += MW_CMSIS
COMPONENTS += MW_CONNECTIVITY_UTILITIES
COMPONENTS += MW_CORE_LIB
COMPONENTS += MW_CORE_MAKE
COMPONENTS += MW_MTB_DSL_PSE8XXGP
COMPONENTS += MW_MTB_IPC
COMPONENTS += MW_MTB_SRF
COMPONENTS += MW_SE_RT_SERVICES_UTILS
COMPONENTS += MW_SPEECH_ONSET_DETECTION

# Register map file
DEVICE_PSE846GPS2DBZC4A_SVD=$(SEARCH_mtb-dsl-pse8xxgp)/pdl/svd/pse84.svd


#
# generate make targets for the graphical editors that are specific to this project
#

bsp-assistant:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name bsp-assistant
.PHONY: bsp-assistant

CY_HELP_bsp-assistant=Launches the BSP Assistant 1.50 GUI
CY_HELP_bsp-assistant_VERBOSE=Launches the BSP Assistant 1.50 GUI. Check the BSP Assistant 1.50 User Guide for more information.
mtb_help_tool_bsp-assistant:
	@:
	$(info $(MTB__SPACE)bsp-assistant       $(CY_HELP_bsp-assistant))

mtb_help_tools_end: mtb_help_tool_bsp-assistant
mtb_help_tool_bsp-assistant: mtb_help_tools_start
.PHONY: mtb_help_tool_bsp-assistant

config_bt:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name bt-configurator
.PHONY: config_bt

CY_HELP_config_bt=Launches the Bluetooth® Configurator 3.40 GUI for the target's cybt file
CY_HELP_config_bt_VERBOSE=Launches the Bluetooth® Configurator 3.40 GUI. Check the Bluetooth® Configurator 3.40 User Guide for more information.
mtb_help_tool_config_bt:
	@:
	$(info $(MTB__SPACE)config_bt           $(CY_HELP_config_bt))

mtb_help_tools_end: mtb_help_tool_config_bt
mtb_help_tool_config_bt: mtb_help_tools_start
.PHONY: mtb_help_tool_config_bt

bt-configurator:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name bt-configurator
.PHONY: bt-configurator

CY_HELP_bt-configurator=Launches the Bluetooth® Configurator 3.40 GUI for the target's cybt file
CY_HELP_bt-configurator_VERBOSE=Launches the Bluetooth® Configurator 3.40 GUI. Check the Bluetooth® Configurator 3.40 User Guide for more information.
mtb_help_tool_bt-configurator:
	@:
	$(info $(MTB__SPACE)bt-configurator     $(CY_HELP_bt-configurator))

mtb_help_tools_end: mtb_help_tool_bt-configurator
mtb_help_tool_bt-configurator: mtb_help_tools_start
.PHONY: mtb_help_tool_bt-configurator

config:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name device-configurator
.PHONY: config

CY_HELP_config=Launches the Device Configurator 5.50 GUI for the target's modus file
CY_HELP_config_VERBOSE=Launches the Device Configurator 5.50 GUI. Check the Device Configurator 5.50 User Guide for more information.
mtb_help_tool_config:
	@:
	$(info $(MTB__SPACE)config              $(CY_HELP_config))

mtb_help_tools_end: mtb_help_tool_config
mtb_help_tool_config: mtb_help_tools_start
.PHONY: mtb_help_tool_config

device-configurator:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name device-configurator
.PHONY: device-configurator

CY_HELP_device-configurator=Launches the Device Configurator 5.50 GUI for the target's modus file
CY_HELP_device-configurator_VERBOSE=Launches the Device Configurator 5.50 GUI. Check the Device Configurator 5.50 User Guide for more information.
mtb_help_tool_device-configurator:
	@:
	$(info $(MTB__SPACE)device-configurator $(CY_HELP_device-configurator))

mtb_help_tools_end: mtb_help_tool_device-configurator
mtb_help_tool_device-configurator: mtb_help_tools_start
.PHONY: mtb_help_tool_device-configurator

modlibs:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name library-manager
.PHONY: modlibs

CY_HELP_modlibs=Launches the Library Manager 2.50 GUI
CY_HELP_modlibs_VERBOSE=Launches the Library Manager 2.50 GUI. Check the Library Manager 2.50 User Guide for more information.
mtb_help_tool_modlibs:
	@:
	$(info $(MTB__SPACE)modlibs             $(CY_HELP_modlibs))

mtb_help_tools_end: mtb_help_tool_modlibs
mtb_help_tool_modlibs: mtb_help_tools_start
.PHONY: mtb_help_tool_modlibs

library-manager:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name library-manager
.PHONY: library-manager

CY_HELP_library-manager=Launches the Library Manager 2.50 GUI
CY_HELP_library-manager_VERBOSE=Launches the Library Manager 2.50 GUI. Check the Library Manager 2.50 User Guide for more information.
mtb_help_tool_library-manager:
	@:
	$(info $(MTB__SPACE)library-manager     $(CY_HELP_library-manager))

mtb_help_tools_end: mtb_help_tool_library-manager
mtb_help_tool_library-manager: mtb_help_tools_start
.PHONY: mtb_help_tool_library-manager

qspi-configurator:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name qspi-configurator
.PHONY: qspi-configurator

CY_HELP_qspi-configurator=Launches the QSPI Configurator 4.60 GUI for the target's cyqspi file
CY_HELP_qspi-configurator_VERBOSE=Launches the QSPI Configurator 4.60 GUI. Check the QSPI Configurator 4.60 User Guide for more information.
mtb_help_tool_qspi-configurator:
	@:
	$(info $(MTB__SPACE)qspi-configurator   $(CY_HELP_qspi-configurator))

mtb_help_tools_end: mtb_help_tool_qspi-configurator
mtb_help_tool_qspi-configurator: mtb_help_tools_start
.PHONY: mtb_help_tool_qspi-configurator

smartio-configurator:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name smartio-configurator
.PHONY: smartio-configurator

CY_HELP_smartio-configurator=Launches the Smart I/O Configurator 4.50 GUI for the target's modus file
CY_HELP_smartio-configurator_VERBOSE=Launches the Smart I/O Configurator 4.50 GUI. Check the Smart I/O Configurator 4.50 User Guide for more information.
mtb_help_tool_smartio-configurator:
	@:
	$(info $(MTB__SPACE)smartio-configurator $(CY_HELP_smartio-configurator))

mtb_help_tools_end: mtb_help_tool_smartio-configurator
mtb_help_tool_smartio-configurator: mtb_help_tools_start
.PHONY: mtb_help_tool_smartio-configurator

config_ml:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name ml-configurator
.PHONY: config_ml

CY_HELP_config_ml=Launches the ML Configurator 3.0 GUI for the target's mtbml file
CY_HELP_config_ml_VERBOSE=Launches the ML Configurator 3.0 GUI. Check the ML Configurator 3.0 User Guide for more information.
mtb_help_tool_config_ml:
	@:
	$(info $(MTB__SPACE)config_ml           $(CY_HELP_config_ml))

mtb_help_tools_end: mtb_help_tool_config_ml
mtb_help_tool_config_ml: mtb_help_tools_start
.PHONY: mtb_help_tool_config_ml

ml-configurator:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name ml-configurator
.PHONY: ml-configurator

CY_HELP_ml-configurator=Launches the ML Configurator 3.0 GUI for the target's mtbml file
CY_HELP_ml-configurator_VERBOSE=Launches the ML Configurator 3.0 GUI. Check the ML Configurator 3.0 User Guide for more information.
mtb_help_tool_ml-configurator:
	@:
	$(info $(MTB__SPACE)ml-configurator     $(CY_HELP_ml-configurator))

mtb_help_tools_end: mtb_help_tool_ml-configurator
mtb_help_tool_ml-configurator: mtb_help_tools_start
.PHONY: mtb_help_tool_ml-configurator

config_audio-fe:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name audio-fe-configurator
.PHONY: config_audio-fe

CY_HELP_config_audio-fe=Launches the Audio FE Configurator 1.60 GUI for the target's mtbafe file
CY_HELP_config_audio-fe_VERBOSE=Launches the Audio FE Configurator 1.60 GUI. Check the Audio FE Configurator 1.60 User Guide for more information.
mtb_help_tool_config_audio-fe:
	@:
	$(info $(MTB__SPACE)config_audio-fe     $(CY_HELP_config_audio-fe))

mtb_help_tools_end: mtb_help_tool_config_audio-fe
mtb_help_tool_config_audio-fe: mtb_help_tools_start
.PHONY: mtb_help_tool_config_audio-fe

audio-fe-configurator:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name audio-fe-configurator
.PHONY: audio-fe-configurator

CY_HELP_audio-fe-configurator=Launches the Audio FE Configurator 1.60 GUI for the target's mtbafe file
CY_HELP_audio-fe-configurator_VERBOSE=Launches the Audio FE Configurator 1.60 GUI. Check the Audio FE Configurator 1.60 User Guide for more information.
mtb_help_tool_audio-fe-configurator:
	@:
	$(info $(MTB__SPACE)audio-fe-configurator $(CY_HELP_audio-fe-configurator))

mtb_help_tools_end: mtb_help_tool_audio-fe-configurator
mtb_help_tool_audio-fe-configurator: mtb_help_tools_start
.PHONY: mtb_help_tool_audio-fe-configurator

edge-protect-configurator:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name edge-protect-configurator
.PHONY: edge-protect-configurator

CY_HELP_edge-protect-configurator=Launches the Edge Protect Configurator 1.20 GUI for the target's edgeprotect file
CY_HELP_edge-protect-configurator_VERBOSE=Launches the Edge Protect Configurator 1.20 GUI. Check the Edge Protect Configurator 1.20 User Guide for more information.
mtb_help_tool_edge-protect-configurator:
	@:
	$(info $(MTB__SPACE)edge-protect-configurator $(CY_HELP_edge-protect-configurator))

mtb_help_tools_end: mtb_help_tool_edge-protect-configurator
mtb_help_tool_edge-protect-configurator: mtb_help_tools_start
.PHONY: mtb_help_tool_edge-protect-configurator

.PHONY: mtb_help_tools_start mtb_help_tools_end
