<<<<<<< HEAD:proj_cm55/ui/ui_comp_hook.c
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: Thermostat_HMI

=======
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Thermostat_HMI

>>>>>>> e976160882b41277609efcbb0f01c52860d8cd97:proj_cm55/ui/components/ui_comp_hook.c
