// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Thermostat_HMI

#include "ui.h"

void fan_clicked(lv_event_t * e)
{
	// Your code here
}

void toggle_mode(lv_event_t * e)
{
	// Your code here
}

void hide_mapp_info_label(lv_event_t * e)
{
	// Your code here
}

void start_ble_adv(lv_event_t * e)
{
	// Your code here
}

void start_wifi_settings_ilabel_timer(lv_event_t * e)
{
	// Your code here
}

void connect_wifi(lv_event_t * e)
{
	// Your code here
}

void display_qrcode(lv_event_t * e)
{
	// Your code here
}

void open_notifcaiton(lv_event_t * e)
{
	// Your code here
}

void mic_icon_click_handler(lv_event_t * e)
{
	// Your code here
}
