/***************************************************************************//**
* \file DSNS_LSTM_tflm_model_int16x8.h
*
* \brief
* Autogenerated with ml-coretools, this file contains DSNS_LSTM model data.
* Date: 2024-11-18 14:34:09.316276
*******************************************************************************
* \copyright
* Copyright 2024, Cypress Semiconductor Corporation (an Infineon company).
* All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
******************************************************************************/

/*
ml-coretools 3.0.0 based on TensorFlow 2.15.0 and ethos-u-vela 3.11.0
	ml-coretools-middleware-streaming 3.0.0
	ml-coretools-tflm-qemu-images 3.0.0.13330
*/

#ifndef DSNS_LSTM_TFLM_MODEL_INT16X8_H
#define DSNS_LSTM_TFLM_MODEL_INT16X8_H

#include <stdint.h>

#ifdef CY_ML_MODEL_MEM
extern const uint8_t DSNS_LSTM_model_bin[];
#else
extern uint8_t DSNS_LSTM_model_bin[];
#endif // CY_ML_MODEL_MEM

#define DSNS_LSTM_MODEL_BIN_LEN (181824u)
#define DSNS_LSTM_ARENA_SIZE (16384u)

extern uint32_t DSNS_LSTM_model_bin_len;
extern uint32_t DSNS_LSTM_arena_size;

#endif // DSNS_LSTM_TFLM_MODEL_INT16X8_H
