/* This file is automatically generated. */
/* cm55 MPU configuration header. */
#ifndef CYCFG_MPU_cm55_ns_0_H
#define CYCFG_MPU_cm55_ns_0_H

#include <stdint.h>
#include <stddef.h>
#include "cy_sysint.h"
#include "cy_syspm.h"
#include "cy_syslib.h"
#include "cmsis_compiler.h"
#include "armv8m_mpu.h"

void Cy_MpuInit_cm55_ns_0(void);

#endif /* CYCFG_MPU_cm55_ns_0_H */
