/* This file is automatically generated. */
#if !defined(CY_CYCFG_SAU_H)
#define CY_CYCFG_SAU_H
#include "cmsis_compiler.h"
#include "cy_device.h"

#ifdef CY_PDL_TZ_ENABLED

#define CY_SAU_REGION_CNT          (3U)
#define CY_SAU_MAX_REGION_CNT      (8U)

typedef struct {
    uint8_t     reg_num;   /* Region number. */
    uint32_t    base_addr; /* Base address of SAU region. */
    uint32_t    size;      /* Size of SAU region. */
    uint32_t    end_addr;  /* End address of SAU region. */
    bool        nsc;       /* Is this region Non-Secure Callable? */
} cy_sau_config_t; 


void Cy_SauInit(void);
extern const cy_sau_config_t SAU_config[CY_SAU_REGION_CNT];

#endif /* #ifdef CY_PDL_TZ_ENABLED */
#endif /* #if !defined(CY_CYCFG_SAU_H) */

