/* This file is automatically generated. */
#ifndef CYCFG_MPC_H
#define CYCFG_MPC_H
#include <stdbool.h>
#include <stdint.h>
#include "cy_device.h"
#include "cy_mpc.h"

cy_rslt_t Cy_MPC_Init(void);

#endif /* #ifndef CYCFG_MPC_H */
