/* This file is automatically generated. */

#include "cycfg_sau.h"

#ifdef CY_PDL_TZ_ENABLED

#ifdef __ICCARM__

#pragma section = "NSC" 
#ifndef NSC_START_ADDRESS
#define NSC_START_ADDRESS  (uint32_t) (__section_begin("NSC"))
#endif /* NSC_START_ADDRESS */
#ifndef NSC_END_ADDRESS
#define NSC_END_ADDRESS  (uint32_t) (__section_end("NSC"))
#endif /* NSC_END_ADDRESS */

#elif defined(__ARMCC_VERSION)

extern uint32_t Image$$app_codeNsc$$Base;
extern uint32_t Image$$app_codeNsc$$Limit;
#ifndef NSC_START_ADDRESS
#define NSC_START_ADDRESS  (uint32_t)&Image$$app_codeNsc$$Base 
#endif /* NSC_START_ADDRESS */
#ifndef NSC_END_ADDRESS
#define NSC_END_ADDRESS  (uint32_t)&Image$$app_codeNsc$$Limit
#endif /* NSC_END_ADDRESS */

#elif defined(__llvm__) || defined (__GNUC__) 

extern uint32_t __nsc_region_start;
extern uint32_t __nsc_region_end;
#ifndef NSC_START_ADDRESS
#define NSC_START_ADDRESS  (uint32_t)&__nsc_region_start 
#endif /* NSC_START_ADDRESS */
#ifndef NSC_END_ADDRESS
#define NSC_END_ADDRESS  (uint32_t)&__nsc_region_end
#endif /* NSC_END_ADDRESS */

#else
#error "Unsupported toolchain" 
#endif

const cy_sau_config_t SAU_config[CY_SAU_REGION_CNT] = 
{
    {
        .reg_num = 0U,
        .base_addr = 0x00000000U,
        .size = 0x10000000U,
        .end_addr = 0x0FFFFFFFU,
        .nsc = false,
    },
    {
        .reg_num = 1U,
        .base_addr = 0x20000000U,
        .size = 0x10000000U,
        .end_addr = 0x2FFFFFFFU,
        .nsc = false,
    },
    {
        .reg_num = 2U,
        .base_addr = 0x40000000U,
        .size = 0xc0000000U,
        .end_addr = 0xFFFFFFFFU,
        .nsc = false,
    },
};

void Cy_SauInit(void)
{
    SAU->CTRL |= SAU_CTRL_ENABLE_Msk;
    for (uint8_t i = 0U ; i < CY_SAU_REGION_CNT ; i++)
    {
        SAU->RNR = SAU_config[i].reg_num;
        SAU->RBAR = (SAU_config[i].base_addr & SAU_RBAR_BADDR_Msk);
        SAU->RLAR = ((SAU_config[i].end_addr & SAU_RLAR_LADDR_Msk) | \
            (SAU_config[i].nsc ? SAU_RLAR_NSC_Msk : 0U) | SAU_RLAR_ENABLE_Msk);
    }

    if((NSC_END_ADDRESS - NSC_START_ADDRESS > 0)) 
    {
        if(CY_SAU_REGION_CNT < CY_SAU_MAX_REGION_CNT)
        {
            /* Extra handling for NSC region if not empty */
            SAU->RNR = CY_SAU_REGION_CNT; 
            SAU->RBAR = (NSC_START_ADDRESS & SAU_RBAR_BADDR_Msk); 
            SAU->RLAR = ((NSC_END_ADDRESS & SAU_RLAR_LADDR_Msk) | \
                SAU_RLAR_NSC_Msk | SAU_RLAR_ENABLE_Msk ); 
         }
        else
        {
            /* We cannot add the setting because we have used all SAU regions */
            CY_ASSERT(0);
        }
     }
}

#endif /* #ifdef CY_PDL_TZ_ENABLED */

