// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Thermostat_HMI

#ifndef UI_ACTIVESCREEN_H
#define UI_ACTIVESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ActiveScreen
extern void ui_ActiveScreen_screen_init(void);
extern void ui_ActiveScreen_screen_destroy(void);
extern void ui_event_ActiveScreen(lv_event_t * e);
extern lv_obj_t * ui_ActiveScreen;
extern lv_obj_t * ui_activeBGImg;
extern lv_obj_t * ui_activeCO2text;
extern lv_obj_t * ui_activeCO2;
extern lv_obj_t * ui_CO2LevelsImg;
extern lv_obj_t * ui_weathercontainer;
extern lv_obj_t * ui_LocationLabel;
extern lv_obj_t * ui_OutdoorTempLabel;
extern lv_obj_t * ui_WeatherIcon;
extern void ui_event_switchLPscreenBTN(lv_event_t * e);
extern lv_obj_t * ui_switchLPscreenBTN;
extern lv_obj_t * ui_Dateactive;
extern lv_obj_t * ui_TimeHactive;
extern lv_obj_t * ui_TimeMactive;
extern lv_obj_t * ui_presencelbl;
extern lv_obj_t * ui_MainModeLabel;
extern void ui_event_commandlbl(lv_event_t * e);
extern lv_obj_t * ui_commandlbl;
extern void ui_event_FPSarrow(lv_event_t * e);
extern lv_obj_t * ui_FPSarrow;
extern void ui_event_BottomPanel(lv_event_t * e);
extern lv_obj_t * ui_BottomPanel;
extern lv_obj_t * ui_FPSlabel;
extern lv_obj_t * ui_ActivescreenContainer;
extern lv_obj_t * ui_LeftPanel;
extern void ui_event_WifiConnectButton(lv_event_t * e);
extern lv_obj_t * ui_WifiConnectButton;
extern lv_obj_t * ui_connectLabel;
extern lv_obj_t * ui_wifi;
extern lv_obj_t * ui_homewifidisconnimg;
extern lv_obj_t * ui_homecloudconnimg;
extern lv_obj_t * ui_homebleadv;
extern void ui_event_Settingsbutton(lv_event_t * e);
extern lv_obj_t * ui_Settingsbutton;
extern lv_obj_t * ui_settingslbl;
extern lv_obj_t * ui_RightPanel;
extern void ui_event_fanbutton(lv_event_t * e);
extern lv_obj_t * ui_fanbutton;
extern lv_obj_t * ui_fanmodelabel;
extern lv_obj_t * ui_fanoff;
extern lv_obj_t * ui_fanactivehigh;
extern lv_obj_t * ui_fanactivelow;
extern lv_obj_t * ui_fanactivemed;
extern void ui_event_ModeButton(lv_event_t * e);
extern lv_obj_t * ui_ModeButton;
extern lv_obj_t * ui_ModeLabel;
extern lv_obj_t * ui_ArcGroup;
extern lv_obj_t * ui_TemperatureArcBgPanel;
extern lv_obj_t * ui_TemperatureCurrValueLbl;
extern lv_obj_t * ui_DegreeLbl;
extern lv_obj_t * ui_ArcTempIndicator;
extern void ui_event_ArcTempControl(lv_event_t * e);
extern lv_obj_t * ui_ArcTempControl;
extern lv_obj_t * ui_currenttemp;
extern lv_obj_t * ui_autoimg;
extern lv_obj_t * ui_ecoimg;
extern lv_obj_t * ui_rapidimg;
extern lv_obj_t * ui_fanmodeimg;
extern void ui_event_popupoverlay(lv_event_t * e);
extern lv_obj_t * ui_popupoverlay;
extern void ui_event_commissionMapp(lv_event_t * e);
extern lv_obj_t * ui_commissionMapp;
extern lv_obj_t * ui_mappinfolabel;
extern lv_obj_t * ui_devicestatelabel;
extern void ui_event_mappinfobutton(lv_event_t * e);
extern lv_obj_t * ui_mappinfobutton;
extern void ui_event_devicestateimg(lv_event_t * e);
extern lv_obj_t * ui_devicestateimg;
extern void ui_event_switchtoKeybd(lv_event_t * e);
extern lv_obj_t * ui_switchtoKeybd;
extern lv_obj_t * ui_commissionKeyboard;
extern lv_obj_t * ui_keyboardinfolabel;
extern void ui_event_keyboardinfobutton(lv_event_t * e);
extern lv_obj_t * ui_keyboardinfobutton;
extern void ui_event_switchtoMapp(lv_event_t * e);
extern lv_obj_t * ui_switchtoMapp;
extern void ui_event_ssidfield(lv_event_t * e);
extern lv_obj_t * ui_ssidfield;
extern void ui_event_passwordfield(lv_event_t * e);
extern lv_obj_t * ui_passwordfield;
extern lv_obj_t * ui_Keyboard;
extern void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern void ui_event_wifisubmitbtn(lv_event_t * e);
extern lv_obj_t * ui_wifisubmitbtn;
extern lv_obj_t * ui_wifisubmitbtnlabel;
extern lv_obj_t * ui_devconnstatecontianer;
extern lv_obj_t * ui_bleconnected120;
extern lv_obj_t * ui_cloudconnecting;
extern lv_obj_t * ui_Spinner1;
extern lv_obj_t * ui_cloudconnected;
extern lv_obj_t * ui_clouddisconn120;
extern void ui_event_wifideletebtn(lv_event_t * e);
extern lv_obj_t * ui_wifideletebtn;
extern void ui_event_qrcodebtn(lv_event_t * e);
extern lv_obj_t * ui_qrcodebtn;
extern lv_obj_t * ui_wificonnecting120;
extern lv_obj_t * ui_wificonnectedimg;
extern lv_obj_t * ui_bleadv;
extern lv_obj_t * ui_devstateimg;
extern lv_obj_t * ui_devstatelabel;
extern lv_obj_t * ui_connectionprg1;
extern lv_obj_t * ui_connectionprg2;
extern lv_obj_t * ui_connectionprg3;
extern void ui_event_qrcodecontainer(lv_event_t * e);
extern lv_obj_t * ui_qrcodecontainer;
extern lv_obj_t * ui_qrcodelabel;
extern void ui_event_qrcodegobackbtn(lv_event_t * e);
extern lv_obj_t * ui_qrcodegobackbtn;
extern lv_obj_t * ui_bleadvimg;
extern lv_obj_t * ui_wificonnectingimg;
extern lv_obj_t * ui_cloudconnectedimg;
extern lv_obj_t * ui_wifidisabledimg;
extern lv_obj_t * ui_incorrectimg;
extern void ui_event_voicecmdcontainer(lv_event_t * e);
extern lv_obj_t * ui_voicecmdcontainer;
extern lv_obj_t * ui_voicecmdlistpanel;
extern lv_obj_t * ui_Commandlistlabel;
extern lv_obj_t * ui_cmdlistheader;
extern void ui_event_notification(lv_event_t * e);
extern lv_obj_t * ui_notification;
extern void ui_event_notificationlabel(lv_event_t * e);
extern lv_obj_t * ui_notificationlabel;
extern lv_obj_t * ui_notificationlblimg;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

