// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Thermostat_HMI

#include "../ui.h"

lv_obj_t * uic_ResetButton;
lv_obj_t * ui_SettingsScreen = NULL;
lv_obj_t * ui_BrightnessSlider = NULL;
lv_obj_t * ui_brightnessimg = NULL;
lv_obj_t * ui_timeoutdropdown = NULL;
lv_obj_t * ui_VolumeDrodown = NULL;
lv_obj_t * ui_Timeoutlbl = NULL;
lv_obj_t * ui_Volumelbl = NULL;
lv_obj_t * ui_tempunitswitch = NULL;
lv_obj_t * ui_BGswitch = NULL;
lv_obj_t * ui_templabel = NULL;
lv_obj_t * ui_BGlabel = NULL;
lv_obj_t * ui_ResetButton = NULL;
lv_obj_t * ui_UpdateButton = NULL;
lv_obj_t * ui_InfoButton = NULL;
lv_obj_t * ui_homeimg2 = NULL;
lv_obj_t * ui_factoryresetcontianer = NULL;
lv_obj_t * ui_Factoryresetlabel = NULL;
lv_obj_t * ui_warninglabel = NULL;
lv_obj_t * ui_confirmbtnlabel = NULL;
lv_obj_t * ui_cancelbtnlabel = NULL;
lv_obj_t * ui_BottomPanel2 = NULL;
lv_obj_t * ui_FPSlabel2 = NULL;
// event funtions
void ui_event_BrightnessSlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        change_brightness(e);
    }
}

void ui_event_timeoutdropdown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        change_idle_timeout(e);
    }
}

void ui_event_VolumeDrodown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        change_volume(e);
    }
}

void ui_event_tempunitswitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        set_system_unit(e);
    }
}

void ui_event_BGswitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        set_background(e);
    }
}

void ui_event_ResetButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_factoryresetcontianer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_UpdateButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_FWUpdateScreen, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0, &ui_FWUpdateScreen_screen_init);
    }
}

void ui_event_homeimg2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ActiveScreen, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_ActiveScreen_screen_init);
    }
}

void ui_event_confirmbtnlabel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_factoryresetcontianer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        device_factory_reset(e);
    }
}

void ui_event_cancelbtnlabel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_factoryresetcontianer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

// build funtions

void ui_SettingsScreen_screen_init(void)
{
    ui_SettingsScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_SettingsScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SettingsScreen, lv_color_hex(0x06534B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingsScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrightnessSlider = lv_slider_create(ui_SettingsScreen);
    lv_slider_set_value(ui_BrightnessSlider, 30, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_BrightnessSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_BrightnessSlider, 0,
                                                                                                     LV_ANIM_OFF);
    lv_obj_set_width(ui_BrightnessSlider, 287);
    lv_obj_set_height(ui_BrightnessSlider, 63);
    lv_obj_set_x(ui_BrightnessSlider, -7);
    lv_obj_set_y(ui_BrightnessSlider, 110);
    lv_obj_set_align(ui_BrightnessSlider, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_BrightnessSlider, lv_color_hex(0x06A366), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrightnessSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_BrightnessSlider, lv_color_hex(0x50FC7C), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_BrightnessSlider, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_BrightnessSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_BrightnessSlider, LV_GRAD_DIR_VER, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_BrightnessSlider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrightnessSlider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_BrightnessSlider, 80, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_BrightnessSlider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_BrightnessSlider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_BrightnessSlider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_BrightnessSlider, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_BrightnessSlider,
                                                                                                       lv_obj_get_style_pad_right(ui_BrightnessSlider, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_brightnessimg = lv_image_create(ui_BrightnessSlider);
    lv_image_set_src(ui_brightnessimg, &ui_img_brightness_png);
    lv_obj_set_width(ui_brightnessimg, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_brightnessimg, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_brightnessimg, -104);
    lv_obj_set_y(ui_brightnessimg, 1);
    lv_obj_set_align(ui_brightnessimg, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_brightnessimg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_timeoutdropdown = lv_dropdown_create(ui_SettingsScreen);
    lv_dropdown_set_dir(ui_timeoutdropdown, LV_DIR_TOP);
    lv_dropdown_set_options(ui_timeoutdropdown, "03 s\n05 s\n10 s\n20 s\n30 s\nNever");
    lv_obj_set_width(ui_timeoutdropdown, 96);
    lv_obj_set_height(ui_timeoutdropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timeoutdropdown, -179);
    lv_obj_set_y(ui_timeoutdropdown, -179);
    lv_obj_set_align(ui_timeoutdropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_timeoutdropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_timeoutdropdown, lv_color_hex(0xFDF9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_timeoutdropdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_timeoutdropdown, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_timeoutdropdown, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_timeoutdropdown, lv_color_hex(0x0BCBAC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_timeoutdropdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_timeoutdropdown, lv_color_hex(0x0D9A30), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_timeoutdropdown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_timeoutdropdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_timeoutdropdown, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_timeoutdropdown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VolumeDrodown = lv_dropdown_create(ui_SettingsScreen);
    lv_dropdown_set_dir(ui_VolumeDrodown, LV_DIR_TOP);
    lv_dropdown_set_options(ui_VolumeDrodown, "OFF\nLOW\nMED\nHIGH");
    lv_obj_set_width(ui_VolumeDrodown, 99);
    lv_obj_set_height(ui_VolumeDrodown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VolumeDrodown, 150);
    lv_obj_set_y(ui_VolumeDrodown, -180);
    lv_obj_set_align(ui_VolumeDrodown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_VolumeDrodown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_VolumeDrodown, lv_color_hex(0xFAF9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VolumeDrodown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VolumeDrodown, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_VolumeDrodown, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_VolumeDrodown, lv_color_hex(0x0BCBAC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VolumeDrodown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_VolumeDrodown, lv_color_hex(0x0D9A30), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_VolumeDrodown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_VolumeDrodown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_VolumeDrodown, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_VolumeDrodown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Timeoutlbl = lv_label_create(ui_SettingsScreen);
    lv_obj_set_width(ui_Timeoutlbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Timeoutlbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Timeoutlbl, -182);
    lv_obj_set_y(ui_Timeoutlbl, -218);
    lv_obj_set_align(ui_Timeoutlbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Timeoutlbl, "Timeout");
    lv_obj_set_style_text_color(ui_Timeoutlbl, lv_color_hex(0xFDF7F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Timeoutlbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Timeoutlbl, &ui_font_sans22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Volumelbl = lv_label_create(ui_SettingsScreen);
    lv_obj_set_width(ui_Volumelbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Volumelbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Volumelbl, 147);
    lv_obj_set_y(ui_Volumelbl, -218);
    lv_obj_set_align(ui_Volumelbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Volumelbl, "Volume");
    lv_obj_set_style_text_color(ui_Volumelbl, lv_color_hex(0xFDF7F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Volumelbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Volumelbl, &ui_font_sans22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempunitswitch = lv_switch_create(ui_SettingsScreen);
    lv_obj_set_width(ui_tempunitswitch, 51);
    lv_obj_set_height(ui_tempunitswitch, 25);
    lv_obj_set_x(ui_tempunitswitch, -206);
    lv_obj_set_y(ui_tempunitswitch, 202);
    lv_obj_set_align(ui_tempunitswitch, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_tempunitswitch, lv_color_hex(0xC8C3C3), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tempunitswitch, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_BGswitch = lv_switch_create(ui_SettingsScreen);
    lv_obj_set_width(ui_BGswitch, 50);
    lv_obj_set_height(ui_BGswitch, 25);
    lv_obj_set_x(ui_BGswitch, 184);
    lv_obj_set_y(ui_BGswitch, 201);
    lv_obj_set_align(ui_BGswitch, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_BGswitch, LV_STATE_CHECKED);       /// States

    ui_templabel = lv_label_create(ui_SettingsScreen);
    lv_obj_set_width(ui_templabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_templabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_templabel, -163);
    lv_obj_set_y(ui_templabel, 205);
    lv_obj_set_align(ui_templabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_templabel, "°F");
    lv_obj_set_style_text_color(ui_templabel, lv_color_hex(0xF8F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_templabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_templabel, &ui_font_sans28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BGlabel = lv_label_create(ui_SettingsScreen);
    lv_obj_set_width(ui_BGlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BGlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BGlabel, 137);
    lv_obj_set_y(ui_BGlabel, 203);
    lv_obj_set_align(ui_BGlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BGlabel, "BG");
    lv_obj_set_style_text_color(ui_BGlabel, lv_color_hex(0xF8F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BGlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BGlabel, &ui_font_sans28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResetButton = lv_button_create(ui_SettingsScreen);
    lv_obj_set_width(ui_ResetButton, 77);
    lv_obj_set_height(ui_ResetButton, 72);
    lv_obj_set_x(ui_ResetButton, -106);
    lv_obj_set_y(ui_ResetButton, -31);
    lv_obj_set_align(ui_ResetButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ResetButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ResetButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ResetButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ResetButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_ResetButton, &ui_img_undo_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_ResetButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_ResetButton, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ResetButton, lv_color_hex(0x30AD29), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ResetButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ResetButton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ResetButton, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ResetButton, lv_color_hex(0x06AD63), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ResetButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ResetButton, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ResetButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_rotation(ui_ResetButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UpdateButton = lv_button_create(ui_SettingsScreen);
    lv_obj_set_width(ui_UpdateButton, 77);
    lv_obj_set_height(ui_UpdateButton, 72);
    lv_obj_set_x(ui_UpdateButton, -5);
    lv_obj_set_y(ui_UpdateButton, -31);
    lv_obj_set_align(ui_UpdateButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_UpdateButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_UpdateButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_UpdateButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_UpdateButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_UpdateButton, &ui_img_149480563, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_UpdateButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_UpdateButton, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_UpdateButton, lv_color_hex(0x30AD29), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_UpdateButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_UpdateButton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_UpdateButton, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_UpdateButton, lv_color_hex(0x06AD63), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_UpdateButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_UpdateButton, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_UpdateButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_rotation(ui_UpdateButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_InfoButton = lv_button_create(ui_SettingsScreen);
    lv_obj_set_width(ui_InfoButton, 77);
    lv_obj_set_height(ui_InfoButton, 72);
    lv_obj_set_x(ui_InfoButton, 96);
    lv_obj_set_y(ui_InfoButton, -31);
    lv_obj_set_align(ui_InfoButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_InfoButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_InfoButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_InfoButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_InfoButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_InfoButton, &ui_img_info_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_InfoButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_InfoButton, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_InfoButton, lv_color_hex(0x30AD29), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_InfoButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_InfoButton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_InfoButton, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_InfoButton, lv_color_hex(0x06AD63), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_InfoButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_InfoButton, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_InfoButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_rotation(ui_InfoButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_homeimg2 = lv_image_create(ui_SettingsScreen);
    lv_image_set_src(ui_homeimg2, &ui_img_icn_home_png);
    lv_obj_set_width(ui_homeimg2, 70);
    lv_obj_set_height(ui_homeimg2, 70);
    lv_obj_set_x(ui_homeimg2, -11);
    lv_obj_set_y(ui_homeimg2, -202);
    lv_obj_set_align(ui_homeimg2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_homeimg2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_homeimg2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_factoryresetcontianer = lv_obj_create(ui_SettingsScreen);
    lv_obj_remove_style_all(ui_factoryresetcontianer);
    lv_obj_set_width(ui_factoryresetcontianer, 441);
    lv_obj_set_height(ui_factoryresetcontianer, 242);
    lv_obj_set_x(ui_factoryresetcontianer, -16);
    lv_obj_set_y(ui_factoryresetcontianer, 25);
    lv_obj_set_align(ui_factoryresetcontianer, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_factoryresetcontianer, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_factoryresetcontianer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_factoryresetcontianer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_factoryresetcontianer, lv_color_hex(0x212020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_factoryresetcontianer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Factoryresetlabel = lv_label_create(ui_factoryresetcontianer);
    lv_obj_set_width(ui_Factoryresetlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Factoryresetlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Factoryresetlabel, -4);
    lv_obj_set_y(ui_Factoryresetlabel, -92);
    lv_obj_set_align(ui_Factoryresetlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Factoryresetlabel, "Factory Reset");
    lv_obj_set_style_text_color(ui_Factoryresetlabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Factoryresetlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Factoryresetlabel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Factoryresetlabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Factoryresetlabel, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Factoryresetlabel, &ui_font_sans22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_warninglabel = lv_label_create(ui_factoryresetcontianer);
    lv_obj_set_width(ui_warninglabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_warninglabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_warninglabel, 3);
    lv_obj_set_y(ui_warninglabel, -24);
    lv_obj_set_align(ui_warninglabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_warninglabel, "Restore default configuration and \ndelete saved credentials ?");
    lv_obj_set_style_text_color(ui_warninglabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_warninglabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_warninglabel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_warninglabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_warninglabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_warninglabel, &ui_font_sans22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_confirmbtnlabel = lv_label_create(ui_factoryresetcontianer);
    lv_obj_set_width(ui_confirmbtnlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_confirmbtnlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_confirmbtnlabel, 70);
    lv_obj_set_y(ui_confirmbtnlabel, 59);
    lv_obj_set_align(ui_confirmbtnlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_confirmbtnlabel, "Confirm");
    lv_obj_add_flag(ui_confirmbtnlabel, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_confirmbtnlabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_confirmbtnlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_confirmbtnlabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_confirmbtnlabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_confirmbtnlabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_confirmbtnlabel, &ui_font_sans22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_confirmbtnlabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_confirmbtnlabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_confirmbtnlabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_confirmbtnlabel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cancelbtnlabel = lv_label_create(ui_factoryresetcontianer);
    lv_obj_set_width(ui_cancelbtnlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cancelbtnlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cancelbtnlabel, -78);
    lv_obj_set_y(ui_cancelbtnlabel, 57);
    lv_obj_set_align(ui_cancelbtnlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cancelbtnlabel, "Cancel");
    lv_obj_add_flag(ui_cancelbtnlabel, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_cancelbtnlabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cancelbtnlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_cancelbtnlabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_cancelbtnlabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_cancelbtnlabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cancelbtnlabel, &ui_font_sans22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BottomPanel2 = lv_obj_create(ui_SettingsScreen);
    lv_obj_set_width(ui_BottomPanel2, 152);
    lv_obj_set_height(ui_BottomPanel2, 24);
    lv_obj_set_x(ui_BottomPanel2, -10);
    lv_obj_set_y(ui_BottomPanel2, 215);
    lv_obj_set_align(ui_BottomPanel2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BottomPanel2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_BottomPanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BottomPanel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BottomPanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BottomPanel2, lv_color_hex(0x9BBA43), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BottomPanel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FPSlabel2 = lv_label_create(ui_BottomPanel2);
    lv_obj_set_width(ui_FPSlabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FPSlabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FPSlabel2, -1);
    lv_obj_set_y(ui_FPSlabel2, 0);
    lv_obj_set_align(ui_FPSlabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FPSlabel2, "FPS: 40  CPU: 20%");
    lv_obj_set_style_text_color(ui_FPSlabel2, lv_color_hex(0xFDFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FPSlabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BrightnessSlider, ui_event_BrightnessSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_timeoutdropdown, ui_event_timeoutdropdown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_VolumeDrodown, ui_event_VolumeDrodown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_tempunitswitch, ui_event_tempunitswitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BGswitch, ui_event_BGswitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ResetButton, ui_event_ResetButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_UpdateButton, ui_event_UpdateButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_homeimg2, ui_event_homeimg2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_confirmbtnlabel, ui_event_confirmbtnlabel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cancelbtnlabel, ui_event_cancelbtnlabel, LV_EVENT_ALL, NULL);
    uic_ResetButton = ui_ResetButton;

}

void ui_SettingsScreen_screen_destroy(void)
{
    if(ui_SettingsScreen) lv_obj_del(ui_SettingsScreen);

    // NULL screen variables
    ui_SettingsScreen = NULL;
    ui_BrightnessSlider = NULL;
    ui_brightnessimg = NULL;
    ui_timeoutdropdown = NULL;
    ui_VolumeDrodown = NULL;
    ui_Timeoutlbl = NULL;
    ui_Volumelbl = NULL;
    ui_tempunitswitch = NULL;
    ui_BGswitch = NULL;
    ui_templabel = NULL;
    ui_BGlabel = NULL;
    uic_ResetButton = NULL;
    ui_ResetButton = NULL;
    ui_UpdateButton = NULL;
    ui_InfoButton = NULL;
    ui_homeimg2 = NULL;
    ui_factoryresetcontianer = NULL;
    ui_Factoryresetlabel = NULL;
    ui_warninglabel = NULL;
    ui_confirmbtnlabel = NULL;
    ui_cancelbtnlabel = NULL;
    ui_BottomPanel2 = NULL;
    ui_FPSlabel2 = NULL;

}
