// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Thermostat_HMI

#ifndef UI_SETTINGSSCREEN_H
#define UI_SETTINGSSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SettingsScreen
extern void ui_SettingsScreen_screen_init(void);
extern void ui_SettingsScreen_screen_destroy(void);
extern lv_obj_t * ui_SettingsScreen;
extern void ui_event_BrightnessSlider(lv_event_t * e);
extern lv_obj_t * ui_BrightnessSlider;
extern lv_obj_t * ui_brightnessimg;
extern void ui_event_timeoutdropdown(lv_event_t * e);
extern lv_obj_t * ui_timeoutdropdown;
extern void ui_event_VolumeDrodown(lv_event_t * e);
extern lv_obj_t * ui_VolumeDrodown;
extern lv_obj_t * ui_Timeoutlbl;
extern lv_obj_t * ui_Volumelbl;
extern void ui_event_tempunitswitch(lv_event_t * e);
extern lv_obj_t * ui_tempunitswitch;
extern void ui_event_BGswitch(lv_event_t * e);
extern lv_obj_t * ui_BGswitch;
extern lv_obj_t * ui_templabel;
extern lv_obj_t * ui_BGlabel;
extern void ui_event_ResetButton(lv_event_t * e);
extern lv_obj_t * ui_ResetButton;
extern void ui_event_UpdateButton(lv_event_t * e);
extern lv_obj_t * ui_UpdateButton;
extern lv_obj_t * ui_InfoButton;
extern void ui_event_homeimg2(lv_event_t * e);
extern lv_obj_t * ui_homeimg2;
extern lv_obj_t * ui_factoryresetcontianer;
extern lv_obj_t * ui_Factoryresetlabel;
extern lv_obj_t * ui_warninglabel;
extern void ui_event_confirmbtnlabel(lv_event_t * e);
extern lv_obj_t * ui_confirmbtnlabel;
extern void ui_event_cancelbtnlabel(lv_event_t * e);
extern lv_obj_t * ui_cancelbtnlabel;
extern lv_obj_t * ui_BottomPanel2;
extern lv_obj_t * ui_FPSlabel2;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ResetButton;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

