// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: Thermostat_HMI

#ifndef UI_ACTIVESCREEN_H
#define UI_ACTIVESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif



// SCREEN: ui_ActiveScreen
extern void ui_ActiveScreen_screen_init(void);
extern void ui_ActiveScreen_screen_destroy(void);
extern lv_obj_t * ui_ActiveScreen;
extern lv_obj_t * ui_SystemSettings;

extern lv_obj_t * ui_backgroundimage;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_MainTempactive;
extern lv_obj_t * ui_TimeColonactive;
extern lv_obj_t * ui_TimeHactive;
extern lv_obj_t * ui_TimeMactive;
extern lv_obj_t * ui_Dateactive;
extern lv_obj_t * ui_homescreensubmsg;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_humidity;
extern lv_obj_t * ui_weathercontainer2;
extern lv_obj_t * ui_WeatherTextactive2;
extern lv_obj_t * ui_container2text;
extern lv_obj_t * ui_humidity2;
extern lv_obj_t * ui_weatheractive2;
extern lv_obj_t * ui_Image5;
extern void ui_event_swiperightgesture(lv_event_t * e);
extern lv_obj_t * ui_swiperightgesture;
extern lv_obj_t * ui_smalluparrow;
extern lv_obj_t * ui_bigdownarrow;
extern lv_obj_t * ui_Mainroomtextactive;
extern void ui_event_mode(lv_event_t * e);
extern lv_obj_t * ui_mode;
extern lv_obj_t * ui_settings;
extern void ui_event_gesturebutton(lv_event_t * e);
extern lv_obj_t * ui_gesturebutton;
extern lv_obj_t * ui_wifi;
extern lv_obj_t * ui_wifistatic;
extern lv_obj_t * ui_homebleadv;
extern lv_obj_t * ui_homeclouddisconnected;
extern lv_obj_t * ui_homewifidisconnected;
extern lv_obj_t * ui_homecloudconnected;
extern lv_obj_t * ui_smalldownarrow;
extern lv_obj_t * ui_changeroomup;
extern lv_obj_t * ui_changeroomdown;
extern void ui_event_fanbutton(lv_event_t * e);
extern lv_obj_t * ui_fanbutton;
extern lv_obj_t * ui_fanactive;
extern lv_obj_t * ui_fanactivehigh;
extern lv_obj_t * ui_fanactivelow;
extern lv_obj_t * ui_fanactivemed;
extern lv_obj_t * ui_fanmodelabel;
extern lv_obj_t * ui_bluecontainer;
extern lv_obj_t * ui_blue1;
extern lv_obj_t * ui_blue3;
extern lv_obj_t * ui_blue4;
extern lv_obj_t * ui_blue2;
extern lv_obj_t * ui_redcontainer;
extern lv_obj_t * ui_red1;
extern lv_obj_t * ui_red2;
extern lv_obj_t * ui_red3;
extern lv_obj_t * ui_red4;
extern void ui_event_changescreenbuttonACT(lv_event_t * e);
extern lv_obj_t * ui_changescreenbuttonACT;
extern void ui_event_Settingsbutton(lv_event_t * e);
extern lv_obj_t * ui_Settingsbutton;
extern lv_obj_t * ui_currenttemp;
extern void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern void ui_event_weatherbutton(lv_event_t * e);
extern lv_obj_t * ui_weatherbutton;
extern void ui_event_popupoverlay(lv_event_t * e);
extern lv_obj_t * ui_popupoverlay;
extern lv_obj_t * ui_popupbox;
extern void ui_event_commissionMapp(lv_event_t * e);
extern lv_obj_t * ui_commissionMapp;
extern void ui_event_devicestateicon(lv_event_t * e);
extern lv_obj_t * ui_devicestateicon;
extern lv_obj_t * ui_devicestatelabel;
extern void ui_event_devicestateimg(lv_event_t * e);
extern lv_obj_t * ui_devicestateimg;
extern void ui_event_switchtoKeybd(lv_event_t * e);
extern lv_obj_t * ui_switchtoKeybd;
extern lv_obj_t * ui_keybdimg;
extern void ui_event_mappinfobutton(lv_event_t * e);
extern lv_obj_t * ui_mappinfobutton;
extern lv_obj_t * ui_mappinfoicon;
extern lv_obj_t * ui_mappinfolabel;
extern lv_obj_t * ui_commissionKeyboard;
extern void ui_event_switchtoMapp(lv_event_t * e);
extern lv_obj_t * ui_switchtoMapp;
extern lv_obj_t * ui_mobileappimg;
extern void ui_event_ssidfield(lv_event_t * e);
extern lv_obj_t * ui_ssidfield;
extern void ui_event_passwordfield(lv_event_t * e);
extern lv_obj_t * ui_passwordfield;
extern lv_obj_t * ui_Keyboard;
extern void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern void ui_event_wifisubmitbtn(lv_event_t * e);
extern lv_obj_t * ui_wifisubmitbtn;
extern lv_obj_t * ui_wifisubmitbtnlabel;
extern lv_obj_t * ui_keyboardinfoimg;
extern void ui_event_keyboardinfobutton(lv_event_t * e);
extern lv_obj_t * ui_keyboardinfobutton;
extern lv_obj_t * ui_keyboardinfolabel;
extern lv_obj_t * ui_devconnstatecontianer;
extern lv_obj_t * ui_cloudconnected;
extern lv_obj_t * ui_wificonnecting120;
extern lv_obj_t * ui_clouddisconn120;
extern void ui_event_qrcodebtn(lv_event_t * e);
extern lv_obj_t * ui_qrcodebtn;
extern lv_obj_t * ui_qrcodeicon;
extern lv_obj_t * ui_bleadv;
extern lv_obj_t * ui_devstateimg;
extern lv_obj_t * ui_devstatelabel;
extern lv_obj_t * ui_wificonnectedimg;
extern lv_obj_t * ui_wifidisccconnectedimg;
extern lv_obj_t * ui_bleconnected120;
extern lv_obj_t * ui_bleconnected50;
extern lv_obj_t * ui_wifideletebtn;
extern lv_obj_t * ui_qrcodeicon1;
extern lv_obj_t * ui_cloudconnecting;
extern lv_obj_t * ui_Spinner1;
extern lv_obj_t * ui_connectionprg1;
extern lv_obj_t * ui_connectionprg2;
extern lv_obj_t * ui_connectionprg3;
extern lv_obj_t * ui_progressCancelBtn;
extern lv_obj_t * ui_progressCancelImg;
extern lv_obj_t * ui_progressCancelLbl;
extern lv_obj_t * ui_autoreconnectpanel;
extern lv_obj_t * ui_switchtowififromble;
extern lv_obj_t * ui_wifiswitch;
extern lv_obj_t * ui_switchtowififrombleinfolbl;
extern lv_obj_t * ui_autoreconnectlbl;
extern lv_obj_t * ui_Switch2;
extern lv_obj_t * ui_connstatekeyboardbtn;
extern lv_obj_t * ui_connstatekeybdimg;
extern lv_obj_t * ui_blepairingcode;
extern lv_obj_t * ui_titlelabel;
extern lv_obj_t * ui_pinlabel;
extern lv_obj_t * ui_instructionlabel;
extern void ui_event_qrcodecontainer(lv_event_t * e);
extern lv_obj_t * ui_qrcodecontainer;
extern lv_obj_t * ui_qrcodelabel;
extern void ui_event_qrcodegobackbtn(lv_event_t * e);
extern lv_obj_t * ui_qrcodegobackbtn;
extern lv_obj_t * ui_qrgobackimg;
extern lv_obj_t * ui_presence;
extern lv_obj_t * ui_presencecountcircle;
extern lv_obj_t * ui_presencecountlabel;
extern lv_obj_t * ui_micdisabled;
extern void ui_event_notification(lv_event_t * e);
extern lv_obj_t * ui_notification;
extern void ui_event_notificationlabel(lv_event_t * e);
extern lv_obj_t * ui_notificationlabel;
extern lv_obj_t * ui_notificationlblimg;
extern void ui_event_micbutton(lv_event_t * e);
extern lv_obj_t * ui_micbutton;
extern lv_obj_t * ui_bleadvimg;
extern lv_obj_t * ui_wificonnectingimg;
extern lv_obj_t * ui_cloudconnectedimg;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_Image13;
extern lv_obj_t * ui_micactivelisten;
extern lv_obj_t * ui_Image15;
extern lv_obj_t * ui_Image16;
extern lv_obj_t * ui_Image17;
extern lv_obj_t * ui_Image18;
extern lv_obj_t * ui_Image19;
extern lv_obj_t * ui_Image20;
extern lv_obj_t * ui_Image23;
extern lv_obj_t * ui_micidle;
extern lv_obj_t * ui_settingslbl;
extern lv_obj_t * ui_presenclbl;
extern lv_obj_t * ui_modelbl;
extern lv_obj_t * ui_commandlbl;
extern lv_obj_t * ui_connectlbl;
extern lv_obj_t * ui_settolbl;
extern lv_obj_t * ui_temperaturearc;
extern void ui_event_voicecmdoverlaycontainer(lv_event_t * e);
extern lv_obj_t * ui_voicecmdoverlaycontainer;
extern lv_obj_t * ui_voicecmdoverlaysubcontainer;
extern lv_obj_t * ui_voicecmdlistbox;
extern lv_obj_t * ui_vccmd1;
extern lv_obj_t * ui_vccmd2;
extern lv_obj_t * ui_vccmd3;
extern lv_obj_t * ui_vccmd4;
extern lv_obj_t * ui_vccmd5;
extern lv_obj_t * ui_vccmd6;
extern lv_obj_t * ui_vccmd7;
extern lv_obj_t * ui_vccmd8;
extern lv_obj_t * ui_vccmd9;
extern lv_obj_t * ui_vccmd10;
extern lv_obj_t * ui_vccmd11;
extern lv_obj_t * ui_vccmd12;
extern lv_obj_t * ui_vccmd13;
extern lv_obj_t * ui_vccmd14;
extern lv_obj_t * ui_vccmd15;
extern void start_active_state_timer(uint32_t timeout_ms);
extern void stop_active_state_timer(void);
extern lv_obj_t * ui_devstatecontainerssidfield;
extern lv_obj_t * ui_devstatecontainerpasswordfield;
extern lv_obj_t * ui_devstatecontainerwifisubmit;
extern lv_obj_t * ui_wifisubmitbtnlabel1;
extern lv_obj_t * ui_devstatecontainerkeybd;
extern lv_obj_t * ui_devstatecontainerkeybdok;
extern lv_obj_t * ui_devcontainerkeybdgoback;
extern lv_obj_t * ui_devcontainerkeybdgobackimg;
extern lv_obj_t * ui_devconwificonnectionscreen;
extern lv_obj_t * ui_activeCO2;
extern lv_obj_t * ui_activeCO2text;
extern lv_obj_t * ui_homebleconnected;
extern lv_obj_t * ui_bleswitchbtn;
extern lv_obj_t * ui_bleswitchbtnicon;
extern lv_obj_t * ui_bleconswitchtoKeybd;
extern lv_obj_t * ui_bleconkeybdimg;
extern lv_obj_t * ui_bleconmappinfolabel;
extern lv_obj_t * ui_TempArcContanier;
extern lv_obj_t * ui_arcbg;
extern lv_obj_t * ui_tempbg;
extern lv_obj_t * ui_tempnumbg;
extern lv_obj_t * ui_MainTempactive;
extern lv_obj_t * ui_temperaturearc;
extern lv_obj_t * ui_heatingtemparc;
extern lv_obj_t * ui_coolingtemparc;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Panel5;

// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

