// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: Thermostat_HMI

#ifndef UI_AUDIOSETTINGS_H
#define UI_AUDIOSETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_AudioSettings
extern void ui_AudioSettings_screen_init(void);
extern void ui_AudioSettings_screen_destroy(void);
extern lv_obj_t * ui_AudioSettings;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_Label20;
extern void ui_event_backgesture3(lv_event_t * e);
extern lv_obj_t * ui_backgesture3;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Panel17;
extern lv_obj_t * ui_Panel18;
extern lv_obj_t * ui_Panel19;
extern lv_obj_t * ui_Panel20;
extern lv_obj_t * ui_Dropdown1;
extern lv_obj_t * ui_homebtnimg3;
extern void ui_event_homebtn3(lv_event_t * e);
extern lv_obj_t * ui_homebtn3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

