// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: Thermostat_HMI

#ifndef UI_ABOUTSCREEN_H
#define UI_ABOUTSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_AboutScreen
extern void ui_AboutScreen_screen_init(void);
extern void ui_AboutScreen_screen_destroy(void);
extern lv_obj_t * ui_AboutScreen;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_aboutscreenlbl;
extern void ui_event_backgesture2(lv_event_t * e);
extern lv_obj_t * ui_backgesture2;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Panel13;
extern lv_obj_t * ui_Panel15;
extern lv_obj_t * ui_Panel16;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Panel14;
extern lv_obj_t * ui_homebtnimg2;
extern void ui_event_homebtn2(lv_event_t * e);
extern lv_obj_t * ui_homebtn2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

