// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
<<<<<<< HEAD
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
=======
void ui_BootScreen_screen_init(void);
void ui_BootScreen_screen_destroy(void);

>>>>>>> e976160882b41277609efcbb0f01c52860d8cd97
extern lv_obj_t * ui_BootScreen;
extern lv_obj_t * ui_bootcontainer1;
extern lv_obj_t * ui_bootupimg;

// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

