// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: SettingsScreen_HMI

#ifndef UI_DATETIMESETTINGS_H
#define UI_DATETIMESETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_DateTimeSettings
extern void ui_DateTimeSettings_screen_init(void);
extern void ui_DateTimeSettings_screen_destroy(void);
extern lv_obj_t * ui_DateTimeSettings;
extern lv_obj_t * ui_datetimecontainer;
extern lv_obj_t * ui_dateandtimesettinglbl;
extern void ui_event_dateandtimesetting(lv_event_t * e);
extern lv_obj_t * ui_dateandtimesetting;
extern lv_obj_t * ui_dtPanel25;
extern lv_obj_t * ui_dthomebtnimg5;
extern void ui_event_dthomebtn5(lv_event_t * e);
extern lv_obj_t * ui_dthomebtn5;
extern lv_obj_t * ui_Date;
extern void ui_event_datetimetextarea(lv_event_t * e);
extern lv_obj_t * ui_datetimetextarea;
extern lv_obj_t * ui_dtTime;
extern void ui_event_thinc(lv_event_t * e);
extern lv_obj_t * ui_thinc;
extern void ui_event_tminc(lv_event_t * e);
extern lv_obj_t * ui_tminc;
extern void ui_event_tsinc(lv_event_t * e);
extern lv_obj_t * ui_tsinc;
extern void ui_event_thdec(lv_event_t * e);
extern lv_obj_t * ui_thdec;
extern void ui_event_tmdec(lv_event_t * e);
extern lv_obj_t * ui_tmdec;
extern void ui_event_tsdec(lv_event_t * e);
extern lv_obj_t * ui_tsdec;
extern lv_obj_t * ui_htext;
extern lv_obj_t * ui_mtext;
extern lv_obj_t * ui_stext;
extern lv_obj_t * ui_dtcol1;
extern lv_obj_t * ui_dtcol2;
extern void ui_event_dttimeupdtebtn(lv_event_t * e);
extern lv_obj_t * ui_dttimeupdtebtn;
extern lv_obj_t * ui_dtupdatebtnlbl;
extern void ui_event_dtCalendar(lv_event_t * e);
extern lv_obj_t * ui_dtCalendar;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

