// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: Thermostat_HMI

#ifndef UI_FWUPDATESCREEN_H
#define UI_FWUPDATESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_FWUpdateScreen
extern void ui_FWUpdateScreen_screen_init(void);
extern void ui_FWUpdateScreen_screen_destroy(void);
extern lv_obj_t * ui_FWUpdateScreen;
extern lv_obj_t * ui_fwupdtcontinaer;
extern lv_obj_t * ui_fwupdtscreenlbl;
extern void ui_event_backgesture5(lv_event_t * e);
extern lv_obj_t * ui_backgesture5;
extern lv_obj_t * ui_homebtnimg6;
extern void ui_event_homebtn6(lv_event_t * e);
extern lv_obj_t * ui_homebtn6;
extern lv_obj_t * ui_FWUpdatespinner;
extern lv_obj_t * ui_Fwupdatespinrlabel;
extern lv_obj_t * ui_Fwupdatelatestlbl;
extern lv_obj_t * ui_Fwupdateavaillabel;
extern lv_obj_t * ui_fwdownloadbtn;
extern lv_obj_t * ui_fwdownloadbtnlbl;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

