// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Thermostat_HMI

#include "../ui.h"

lv_obj_t * ui_FWUpdateScreen = NULL;
lv_obj_t * ui_homeimg = NULL;
lv_obj_t * ui_FWUpdatespinner = NULL;
lv_obj_t * ui_Fwupdatespinrlabel = NULL;
lv_obj_t * ui_Fwupdatelatestlbl = NULL;
lv_obj_t * ui_fwdownloadbtnlbl = NULL;
lv_obj_t * ui_BottomPanel3 = NULL;
lv_obj_t * ui_FPSlabel3 = NULL;
// event funtions
void ui_event_homeimg(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ActiveScreen, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_ActiveScreen_screen_init);
    }
}

void ui_event_fwdownloadbtnlbl(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        start_ota_process(e);
    }
}

// build funtions

void ui_FWUpdateScreen_screen_init(void)
{
    ui_FWUpdateScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_FWUpdateScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_FWUpdateScreen, lv_color_hex(0x06534B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FWUpdateScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_homeimg = lv_image_create(ui_FWUpdateScreen);
    lv_image_set_src(ui_homeimg, &ui_img_icn_home_png);
    lv_obj_set_width(ui_homeimg, 70);
    lv_obj_set_height(ui_homeimg, 70);
    lv_obj_set_x(ui_homeimg, -10);
    lv_obj_set_y(ui_homeimg, -204);
    lv_obj_set_align(ui_homeimg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_homeimg, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_homeimg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_FWUpdatespinner = lv_spinner_create(ui_FWUpdateScreen);
    //lv_spinner_set_anim_params(ui_FWUpdatespinner, 1000, 90);
    lv_obj_set_width(ui_FWUpdatespinner, 80);
    lv_obj_set_height(ui_FWUpdatespinner, 80);
    lv_obj_set_x(ui_FWUpdatespinner, -9);
    lv_obj_set_y(ui_FWUpdatespinner, -40);
    lv_obj_set_align(ui_FWUpdatespinner, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_FWUpdatespinner, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_color(ui_FWUpdatespinner, lv_color_hex(0xFCFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_FWUpdatespinner, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_FWUpdatespinner, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_FWUpdatespinner, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_FWUpdatespinner, lv_color_hex(0x12A24A), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_FWUpdatespinner, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_FWUpdatespinner, 11, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Fwupdatespinrlabel = lv_label_create(ui_FWUpdateScreen);
    lv_obj_set_width(ui_Fwupdatespinrlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Fwupdatespinrlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Fwupdatespinrlabel, 2);
    lv_obj_set_y(ui_Fwupdatespinrlabel, 50);
    lv_obj_set_align(ui_Fwupdatespinrlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Fwupdatespinrlabel, "Checking for updates . . .");
    lv_obj_set_style_text_color(ui_Fwupdatespinrlabel, lv_color_hex(0xFEFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Fwupdatespinrlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Fwupdatespinrlabel, &ui_font_sans30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Fwupdatelatestlbl = lv_label_create(ui_FWUpdateScreen);
    lv_obj_set_width(ui_Fwupdatelatestlbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Fwupdatelatestlbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Fwupdatelatestlbl, -14);
    lv_obj_set_y(ui_Fwupdatelatestlbl, -80);
    lv_obj_set_align(ui_Fwupdatelatestlbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Fwupdatelatestlbl, "Firmware is up to date.");
    lv_obj_add_flag(ui_Fwupdatelatestlbl, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_Fwupdatelatestlbl, &ui_font_sans30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Fwupdatelatestlbl, lv_color_hex(0xFEFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fwdownloadbtnlbl = lv_label_create(ui_FWUpdateScreen);
    lv_obj_set_width(ui_fwdownloadbtnlbl, 176);
    lv_obj_set_height(ui_fwdownloadbtnlbl, 54);
    lv_obj_set_x(ui_fwdownloadbtnlbl, -11);
    lv_obj_set_y(ui_fwdownloadbtnlbl, -15);
    lv_obj_set_align(ui_fwdownloadbtnlbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_fwdownloadbtnlbl, "Download");
    lv_obj_add_flag(ui_fwdownloadbtnlbl, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_fwdownloadbtnlbl, lv_color_hex(0xFEFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_flag(ui_fwdownloadbtnlbl, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_align(ui_fwdownloadbtnlbl, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_fwdownloadbtnlbl, &ui_font_sans24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_fwdownloadbtnlbl, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_fwdownloadbtnlbl, lv_color_hex(0x525050), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fwdownloadbtnlbl, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_fwdownloadbtnlbl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_fwdownloadbtnlbl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_fwdownloadbtnlbl, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_fwdownloadbtnlbl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BottomPanel3 = lv_obj_create(ui_FWUpdateScreen);
    lv_obj_set_width(ui_BottomPanel3, 152);
    lv_obj_set_height(ui_BottomPanel3, 24);
    lv_obj_set_x(ui_BottomPanel3, -10);
    lv_obj_set_y(ui_BottomPanel3, 214);
    lv_obj_set_align(ui_BottomPanel3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BottomPanel3, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_BottomPanel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BottomPanel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BottomPanel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BottomPanel3, lv_color_hex(0x9BBA43), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BottomPanel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FPSlabel3 = lv_label_create(ui_BottomPanel3);
    lv_obj_set_width(ui_FPSlabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FPSlabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FPSlabel3, -1);
    lv_obj_set_y(ui_FPSlabel3, 0);
    lv_obj_set_align(ui_FPSlabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FPSlabel3, "FPS: 40  CPU: 20%");
    lv_obj_set_style_text_color(ui_FPSlabel3, lv_color_hex(0xFDFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FPSlabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_homeimg, ui_event_homeimg, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_fwdownloadbtnlbl, ui_event_fwdownloadbtnlbl, LV_EVENT_ALL, NULL);
}

void ui_FWUpdateScreen_screen_destroy(void)
{
    if(ui_FWUpdateScreen) lv_obj_del(ui_FWUpdateScreen);

    // NULL screen variables
    ui_FWUpdateScreen = NULL;
    ui_homeimg = NULL;
    ui_FWUpdatespinner = NULL;
    ui_Fwupdatespinrlabel = NULL;
    ui_Fwupdatelatestlbl = NULL;
    ui_fwdownloadbtnlbl = NULL;
    ui_BottomPanel3 = NULL;
    ui_FPSlabel3 = NULL;

}
