// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Thermostat_HMI

#ifndef UI_INFOSCREEN_H
#define UI_INFOSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_InfoScreen
extern void ui_InfoScreen_screen_init(void);
extern void ui_InfoScreen_screen_destroy(void);
extern lv_obj_t * ui_InfoScreen;
extern void ui_event_homeimg1(lv_event_t * e);
extern lv_obj_t * ui_homeimg1;
extern lv_obj_t * ui_BottomPanel1;
extern lv_obj_t * ui_FPSlabel1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Switch1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

