// This file was generated by SquareLine Studio
<<<<<<< HEAD
// SquareLine Studio version: SquareLine Studio 1.5.2
=======
// SquareLine Studio version: SquareLine Studio 1.5.4
>>>>>>> e976160882b41277609efcbb0f01c52860d8cd97
// LVGL version: 9.1.0
// Project name: Thermostat_HMI

#ifndef UI_LPSCREEN_H
#define UI_LPSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_LPScreen
extern void ui_LPScreen_screen_init(void);
extern void ui_LPScreen_screen_destroy(void);
extern lv_obj_t * ui_LPScreen;
<<<<<<< HEAD
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_MainTemptextLP;
extern lv_obj_t * ui_TimeColonLP;
extern lv_obj_t * ui_TimeColonLP2;
extern lv_obj_t * ui_TimeHLP;
extern lv_obj_t * ui_TimeMLP;
extern lv_obj_t * ui_TimeSLP;
extern lv_obj_t * ui_ecoLP;
extern lv_obj_t * ui_DateLP;
=======
extern lv_obj_t * ui_LPscreenContainer;
extern lv_obj_t * ui_MainTemptextLP;
extern lv_obj_t * ui_TimeHLP;
extern lv_obj_t * ui_DateLP;
extern lv_obj_t * ui_TimeMLP;
extern lv_obj_t * ui_TimeSLP;
extern lv_obj_t * ui_Co2LP;
>>>>>>> e976160882b41277609efcbb0f01c52860d8cd97
extern void ui_event_changescreenLP(lv_event_t * e);
extern lv_obj_t * ui_changescreenLP;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

