// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Thermostat_HMI

#ifndef UI_LPSCREEN_H
#define UI_LPSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_LPScreen
extern void ui_LPScreen_screen_init(void);
extern void ui_LPScreen_screen_destroy(void);
extern lv_obj_t * ui_LPScreen;
extern lv_obj_t * ui_LPscreenContainer;
extern lv_obj_t * ui_MainTemptextLP;
extern lv_obj_t * ui_DegreeLbl2;
extern lv_obj_t * ui_TimeHLP;
extern lv_obj_t * ui_DateLP;
extern lv_obj_t * ui_TimeMLP;
extern lv_obj_t * ui_TimeSLP;
extern lv_obj_t * ui_LPModelabel;
extern void ui_event_changescreenLP(lv_event_t * e);
extern lv_obj_t * ui_changescreenLP;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

