// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: Thermostat_HMI

#ifndef UI_PERFORMANCESETTINGS_H
#define UI_PERFORMANCESETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_PerformanceSettings
extern void ui_PerformanceSettings_screen_init(void);
extern void ui_PerformanceSettings_screen_destroy(void);
extern lv_obj_t * ui_PerformanceSettings;
extern lv_obj_t * ui_perfomrancesetcontainer;
extern lv_obj_t * ui_perfomrancesetcontainerlbl;
extern void ui_event_perfomrancesetcontainergest(lv_event_t * e);
extern lv_obj_t * ui_perfomrancesetcontainergest;
extern lv_obj_t * ui_Panel25;
extern lv_obj_t * ui_Panel26;
extern lv_obj_t * ui_Panel27;
extern lv_obj_t * ui_Panel28;
extern lv_obj_t * ui_homebtnimg5;
extern void ui_event_homebtn5(lv_event_t * e);
extern lv_obj_t * ui_homebtn5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

