// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: Thermostat_HMI

#ifndef UI_SENSOR_SETTINGS_H
#define UI_SENSOR_SETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Sensor_Settings
extern void ui_Sensor_Settings_screen_init(void);
extern void ui_Sensor_Settings_screen_destroy(void);
extern lv_obj_t * ui_Sensor_Settings;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_sensorscreenlbl;
extern void ui_event_backgesture4(lv_event_t * e);
extern lv_obj_t * ui_backgesture4;
extern lv_obj_t * ui_Panel21;
extern lv_obj_t * ui_Panel22;
extern lv_obj_t * ui_Panel23;
extern lv_obj_t * ui_Panel24;
extern lv_obj_t * ui_homebtnimg4;
extern void ui_event_homebtn4(lv_event_t * e);
extern lv_obj_t * ui_homebtn4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

