// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: SettingsScreen_HMI

#ifndef UI_SETTINGSSCREEN_H
#define UI_SETTINGSSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SettingsScreen
extern void ui_SettingsScreen_screen_init(void);
extern void ui_SettingsScreen_screen_destroy(void);
extern lv_obj_t * ui_SettingsScreen;
extern lv_obj_t * ui_Container3;
extern void ui_event_Slider2(lv_event_t * e);
extern lv_obj_t * ui_Slider2;
extern lv_obj_t * ui_Image4;
extern void ui_event_upimg(lv_event_t * e);
extern lv_obj_t * ui_upimg;
extern void ui_event_timeoutdropdown(lv_event_t * e);
extern lv_obj_t * ui_timeoutdropdown;
extern void ui_event_Dropdown2(lv_event_t * e);
extern lv_obj_t * ui_Dropdown2;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Image6;
extern void ui_event_tempunitswitch(lv_event_t * e);
extern lv_obj_t * ui_tempunitswitch;
extern lv_obj_t * ui_Label3;
extern void ui_event_Image8(lv_event_t * e);
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Image9;
extern void ui_event_reset(lv_event_t * e);
extern lv_obj_t * ui_reset;
extern lv_obj_t * ui_factoryresetcontianer;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label1;
extern void ui_event_confirmbtn2(lv_event_t * e);
extern lv_obj_t * ui_confirmbtn2;
extern lv_obj_t * ui_confirmbtnlbl2;
extern lv_obj_t * ui_cancelbtn2;
extern lv_obj_t * ui_cancelbtnlbl2;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

