// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: SettingsScreen_HMI

#ifndef UI_SYSTEMSETTINGS_H
#define UI_SYSTEMSETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SystemSettings
extern void ui_SystemSettings_screen_init(void);
extern void ui_SystemSettings_screen_destroy(void);
extern lv_obj_t * ui_SystemSettings;
extern lv_obj_t * ui_Container5;
extern void ui_event_backgesture1(lv_event_t * e);
extern lv_obj_t * ui_backgesture1;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Panel9;
extern void ui_event_Label15(lv_event_t * e);
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Panel12;
extern void ui_event_Label16(lv_event_t * e);
extern lv_obj_t * ui_Label16;
extern void ui_event_Label17(lv_event_t * e);
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_homebtnimg1;
extern void ui_event_homebtn1(lv_event_t * e);
extern lv_obj_t * ui_homebtn1;
extern lv_obj_t * ui_tempunitlbl;
extern void ui_event_tempunitswitch(lv_event_t * e);
extern lv_obj_t * ui_tempunitswitch;
extern void ui_event_timeoutdropdown(lv_event_t * e);
extern lv_obj_t * ui_timeoutdropdown;
extern lv_obj_t * ui_factoryresetcontianer;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Label24;
extern void ui_event_confirmbtn(lv_event_t * e);
extern lv_obj_t * ui_confirmbtn;
extern lv_obj_t * ui_confirmbtnlbl;
extern void ui_event_cancelbtn(lv_event_t * e);
extern lv_obj_t * ui_cancelbtn;
extern lv_obj_t * ui_cancelbtnlbl;
extern lv_obj_t * ui_systemscreenlbl;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

