// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: Thermostat_HMI

#ifndef UI_SETTINGSSCREEN_H
#define UI_SETTINGSSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SettingsScreen
extern void ui_SettingsScreen_screen_init(void);
extern void ui_SettingsScreen_screen_destroy(void);
extern lv_obj_t * ui_SettingsScreen;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Label1;
extern void ui_event_Settingsgesture(lv_event_t * e);
extern lv_obj_t * ui_Settingsgesture;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Panel3;
extern void ui_event_Label3(lv_event_t * e);
extern lv_obj_t * ui_Label3;
extern void ui_event_Label6(lv_event_t * e);
extern lv_obj_t * ui_Label6;
extern void ui_event_Label5(lv_event_t * e);
extern lv_obj_t * ui_Label5;
extern void ui_event_Label4(lv_event_t * e);
extern lv_obj_t * ui_Label4;
extern void ui_event_Label11(lv_event_t * e);
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Image1;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

