SET(SOURCES screens/ui_ActiveScreen.c
    screens/ui_SettingsScreen.c
    screens/ui_FWUpdateScreen.c
    screens/ui_LPScreen.c
    ui.c
    components/ui_comp_hook.c
    ui_helpers.c
    ui_events.c
    images/ui_img_background_3_png.c
    images/ui_img_bleadv50_png.c
    images/ui_img_clouddisconnected50_png.c
    images/ui_img_cloudconnected50_png.c
    images/ui_img_left_panel_bg_3_png.c
    images/ui_img_wifi_png.c
    images/ui_img_settings_png.c
    images/ui_img_right_panel_bg_3_png.c
    images/ui_img_fanactive_png.c
    images/ui_img_eco_png.c
    images/ui_img_sun_png.c
    images/ui_img_voice_home_icon_png.c
    images/ui_img_presence_home_icon_png.c
    images/ui_img_mapp_ble_png.c
    images/ui_img_keyboard_icon1_png.c
    images/ui_img_info_img_png.c
    images/ui_img_mapp_icon1_png.c
    images/ui_img_cloudconnected120_png.c
    images/ui_img_wifi100_png.c
    images/ui_img_clouddisconnected120_png.c
    images/ui_img_qrcode_png.c
    images/ui_img_bleadv120_png.c
    images/ui_img_wifidisconn120_png.c
    images/ui_img_wifi_connected_png.c
    images/ui_img_ble_connected_120_png.c
    images/ui_img_wifidelete_png.c
    images/ui_img_cloud_outline_png.c
    images/ui_img_gobackicon_png.c
    images/ui_img_correct_img_png.c
    images/ui_img_ble_adv_img_png.c
    images/ui_img_wifi_connecting_png.c
    images/ui_img_cloud_connected_png.c
    images/ui_img_automode_png_png.c
    images/ui_img_mode_select_eco_png.c
    images/ui_img_mode_select_rapid_png.c
    images/ui_img_wifidisabled1_png.c
    images/ui_img_mic_listening_png.c
    images/ui_img_incorrect_img_png.c
    images/ui_img_mode_select_fan_png.c
    images/ui_img_undo_png.c
    images/ui_img_149480563.c
    images/ui_img_info_png.c
    images/ui_img_icn_home_png.c
    images/ui_img_brightness_png.c
    fonts/ui_font_Roboto80.c
    fonts/ui_font_sans14.c
    fonts/ui_font_sans16.c
    fonts/ui_font_sans22.c
    fonts/ui_font_sans24.c
    fonts/ui_font_sans28.c
    fonts/ui_font_sans30.c
    fonts/ui_font_sans32.c
    fonts/ui_font_sans34.c
    fonts/ui_font_sans36.c)

add_library(ui ${SOURCES})
