// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Thermostat_HMI

#ifndef _THERMOSTAT_HMI_UI_H
#define _THERMOSTAT_HMI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
void fps_monitor_task(lv_timer_t * timerr);
void fandrag_Animation(lv_obj_t * TargetObject, int delay);
void fanspeed_Animation(lv_obj_t * TargetObject, int delay);
void blue1anim_Animation(lv_obj_t * TargetObject, int delay);
void blue2anim_Animation(lv_obj_t * TargetObject, int delay);
void blue3anim_Animation(lv_obj_t * TargetObject, int delay);
void blue4anim_Animation(lv_obj_t * TargetObject, int delay);
void red1anim_Animation(lv_obj_t * TargetObject, int delay);
void red2anim_Animation(lv_obj_t * TargetObject, int delay);
void red3anim_Animation(lv_obj_t * TargetObject, int delay);
void red4anim_Animation(lv_obj_t * TargetObject, int delay);
void fandragup_Animation(lv_obj_t * TargetObject, int delay);
void colonanim_Animation(lv_obj_t * TargetObject, int delay);
void colonanimLP_Animation(lv_obj_t * TargetObject, int delay);
void tes_Animation(lv_obj_t * TargetObject, int delay);
void wifi_Animation(lv_obj_t * TargetObject, int delay);
void colomanimLP2_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_ActiveScreen
void ui_ActiveScreen_screen_init(void);
extern lv_obj_t * ui_ActiveScreen;
extern lv_obj_t * ui_backgroundimage;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_MainTempactive;
extern lv_obj_t * ui_TimeColonactive;
extern lv_obj_t * ui_TimeHactive;
extern lv_obj_t * ui_TimeMactive;
extern lv_obj_t * ui_Dateactive;
extern lv_obj_t * ui_weathercontainer1;
extern lv_obj_t * ui_WeatherTextactive;
extern lv_obj_t * ui_container1text;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_humidity;
extern lv_obj_t * ui_weathercontainer2;
extern lv_obj_t * ui_WeatherTextactive2;
extern lv_obj_t * ui_container2text;
extern lv_obj_t * ui_humidity2;
extern lv_obj_t * ui_weatheractive2;
extern lv_obj_t * ui_weathercontainer3;
extern lv_obj_t * ui_WeatherTextactive3;
extern lv_obj_t * ui_humidity3;
extern lv_obj_t * ui_container3text;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_RoomTempactive;
void ui_event_swiperightgesture(lv_event_t * e);
extern lv_obj_t * ui_swiperightgesture;
extern lv_obj_t * ui_Roomtextactive;
void ui_event_changeroomgesture(lv_event_t * e);
extern lv_obj_t * ui_changeroomgesture;
extern lv_obj_t * ui_smalluparrow;
extern lv_obj_t * ui_bigdownarrow;
extern lv_obj_t * ui_Mainroomtextactive;
extern lv_obj_t * ui_eco;
extern lv_obj_t * ui_settings;
void ui_event_TempIncbutton(lv_event_t * e);
extern lv_obj_t * ui_TempIncbutton;
void ui_event_TempDecbutton(lv_event_t * e);
extern lv_obj_t * ui_TempDecbutton;
extern lv_obj_t * ui_biguparrow;
void ui_event_gesturebutton(lv_event_t * e);
extern lv_obj_t * ui_gesturebutton;
extern lv_obj_t * ui_wifi;
extern lv_obj_t * ui_smalldownarrow;
void ui_event_changeroomup(lv_event_t * e);
extern lv_obj_t * ui_changeroomup;
void ui_event_changeroomdown(lv_event_t * e);
extern lv_obj_t * ui_changeroomdown;
void ui_event_fanbutton(lv_event_t * e);
extern lv_obj_t * ui_fanbutton;
extern lv_obj_t * ui_fanactive;
extern lv_obj_t * ui_bluecontainer;
extern lv_obj_t * ui_blue1;
extern lv_obj_t * ui_blue3;
extern lv_obj_t * ui_blue4;
extern lv_obj_t * ui_blue2;
extern lv_obj_t * ui_redcontainer;
extern lv_obj_t * ui_red1;
extern lv_obj_t * ui_red2;
extern lv_obj_t * ui_red3;
extern lv_obj_t * ui_red4;
void ui_event_changescreenbuttonACT(lv_event_t * e);
extern lv_obj_t * ui_changescreenbuttonACT;
void ui_event_Settingsbutton(lv_event_t * e);
extern lv_obj_t * ui_Settingsbutton;
extern lv_obj_t * ui_currenttemp;
extern lv_obj_t * ui_fanspeedcontainer;
extern lv_obj_t * ui_highbutton;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_medbutton;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_lowbutton;
extern lv_obj_t * ui_Label10;
void ui_event_highbutton(lv_event_t * e);
void ui_event_medbutton(lv_event_t * e);
void ui_event_lowbutton(lv_event_t * e);
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
void ui_event_weatherbutton(lv_event_t * e);
extern lv_obj_t * ui_weatherbutton;
// CUSTOM VARIABLES

// SCREEN: ui_LPScreen
void ui_LPScreen_screen_init(void);
extern lv_obj_t * ui_LPScreen;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_MainTemptextLP;
extern lv_obj_t * ui_TimeColonLP;
extern lv_obj_t * ui_TimeColonLP2;
extern lv_obj_t * ui_TimeHLP;
extern lv_obj_t * ui_TimeMLP;
extern lv_obj_t * ui_TimeSLP;
extern lv_obj_t * ui_ecoLP;
extern lv_obj_t * ui_DateLP;
void ui_event_changescreenLP(lv_event_t * e);
extern lv_obj_t * ui_changescreenLP;
// CUSTOM VARIABLES

// SCREEN: ui_SettingsScreen
void ui_SettingsScreen_screen_init(void);
extern lv_obj_t * ui_SettingsScreen;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label1;
void ui_event_Settingsgesture(lv_event_t * e);
extern lv_obj_t * ui_Settingsgesture;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label6;
void ui_event_Slider1(lv_event_t * e);
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label5;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label4;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_screenbackground_png);    // assets/screenbackground.png
LV_IMG_DECLARE(ui_img_background_png);    // assets/background.png
LV_IMG_DECLARE(ui_img_cloudy_png);    // assets/cloudy.png
LV_IMG_DECLARE(ui_img_sun_png);    // assets/sun.png
LV_IMG_DECLARE(ui_img_rain_png);    // assets/rain.png
LV_IMG_DECLARE(ui_img_209868359);    // assets/white-triangle-icon-small.png
LV_IMG_DECLARE(ui_img_614296446);    // assets/white-triangle-icon-8.png
LV_IMG_DECLARE(ui_img_eco_png);    // assets/eco.png
LV_IMG_DECLARE(ui_img_settings_png);    // assets/settings.png
LV_IMG_DECLARE(ui_img_wifi_png);    // assets/wifi.png
LV_IMG_DECLARE(ui_img_fanactive_png);    // assets/fanactive.png
LV_IMG_DECLARE(ui_img_picture5_png);    // assets/Picture5.png
LV_IMG_DECLARE(ui_img_picture8_png);    // assets/Picture8.png
LV_IMG_DECLARE(ui_img_picture7_png);    // assets/Picture7.png
LV_IMG_DECLARE(ui_img_picture6_png);    // assets/Picture6.png
LV_IMG_DECLARE(ui_img_picture1_png);    // assets/Picture1.png
LV_IMG_DECLARE(ui_img_picture2_png);    // assets/Picture2.png
LV_IMG_DECLARE(ui_img_picture4_png);    // assets/Picture4.png
LV_IMG_DECLARE(ui_img_picture3_png);    // assets/Picture3.png
LV_IMG_DECLARE(ui_img_344061264);    // assets/lowres-House.eps.png

// FONTS
LV_FONT_DECLARE(ui_font_Roboto80);
LV_FONT_DECLARE(ui_font_sans14);
LV_FONT_DECLARE(ui_font_sans16);
LV_FONT_DECLARE(ui_font_sans22);
LV_FONT_DECLARE(ui_font_sans24);
LV_FONT_DECLARE(ui_font_sans28);
LV_FONT_DECLARE(ui_font_sans30);
LV_FONT_DECLARE(ui_font_sans32);
LV_FONT_DECLARE(ui_font_sans34);
LV_FONT_DECLARE(ui_font_sans36);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
