// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Thermostat_HMI

#ifndef _THERMOSTAT_HMI_UI_H
#define _THERMOSTAT_HMI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_ActiveScreen.h"
#include "screens/ui_LPScreen.h"
#include "screens/ui_SettingsScreen.h"
#include "screens/ui_BootScreen.h"
#include "screens/ui_FWUpdateScreen.h"
#include "screens/ui_AboutScreen.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * fanspeed_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * tes_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * wifi_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * bleadvpulse_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * miclisteninganime_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * wificonnectionanim_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * progress1_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * progress2_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * progress3_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * fanspeedlow_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * fanspeedmed_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * fanspeedhigh_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * LeftPanelAnim_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * RightPanelAnim_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * fpsdrag_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * fpsdown_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_temp_arc);    // assets/background_4.png
LV_IMG_DECLARE(ui_img_left_panel_1);    // assets/background_4.png
LV_IMG_DECLARE(ui_img_right_panel_1);    // assets/background_4.png
LV_IMG_DECLARE(ui_img_bleadv50_png);    // assets/bleadv50.png
LV_IMG_DECLARE(ui_img_clouddisconnected50_png);    // assets/clouddisconnected50.png
LV_IMG_DECLARE(ui_img_cloudconnected50_png);    // assets/cloudconnected50.png
LV_IMG_DECLARE(ui_img_wifi_png);    // assets/wifi.png
LV_IMG_DECLARE(ui_img_settings_png);    // assets/settings.png
LV_IMG_DECLARE(ui_img_fanactive_png);    // assets/fanactive.png
LV_IMG_DECLARE(ui_img_eco_png);    // assets/eco.png
LV_IMG_DECLARE(ui_img_uparrow_png);    // assets/uparrow.png
LV_IMG_DECLARE(ui_img_sun_png);    // assets/sun.png
LV_IMG_DECLARE(ui_img_voice_home_icon_png);    // assets/Voice_home_icon.png
LV_IMG_DECLARE(ui_img_presence_home_icon_png);    // assets/presence_home_icon.png
LV_IMG_DECLARE(ui_img_rain_png);    // assets/rain.png
LV_IMG_DECLARE(ui_img_thunder_png);    // assets/Thunder.png
LV_IMG_DECLARE(ui_img_snowflake_png);    // assets/snowflake.png
LV_IMG_DECLARE(ui_img_clear_png);    // assets/clear.png
LV_IMG_DECLARE(ui_img_fog_png);    // assets/fog.png
LV_IMG_DECLARE(ui_img_mapp_ble_png);    // assets/Mapp_ble.png
LV_IMG_DECLARE(ui_img_keyboard_icon1_png);    // assets/keyboard_icon1.png
LV_IMG_DECLARE(ui_img_info_img_png);    // assets/info_img.png
LV_IMG_DECLARE(ui_img_mapp_icon1_png);    // assets/Mapp_icon1.png
LV_IMG_DECLARE(ui_img_cloudconnected120_png);    // assets/cloudconnected120.png
LV_IMG_DECLARE(ui_img_wifi100_png);    // assets/wifi100.png
LV_IMG_DECLARE(ui_img_clouddisconnected120_png);    // assets/clouddisconnected120.png
LV_IMG_DECLARE(ui_img_qrcode_png);    // assets/qrcode.png
LV_IMG_DECLARE(ui_img_bleadv120_png);    // assets/bleadv120.png
LV_IMG_DECLARE(ui_img_bleadv120);    // assets/bleadv120.png
LV_IMG_DECLARE(ui_img_wifidisconn120_png);    // assets/wifidisconn120.png
LV_IMG_DECLARE(ui_img_wifi_connected_png);    // assets/wifi_connected.png
LV_IMG_DECLARE(ui_img_ble_connected_120_png);    // assets/ble_connected_120.png
LV_IMG_DECLARE(ui_img_wifidelete_png);    // assets/wifidelete.png
LV_IMG_DECLARE(ui_img_cloud_outline_png);    // assets/cloud_outline.png
LV_IMG_DECLARE(ui_img_gobackicon_png);    // assets/gobackicon.png
LV_IMG_DECLARE(ui_img_correct_img_png);    // assets/correct_img.png
LV_IMG_DECLARE(ui_img_ble_adv_img_png);    // assets/ble_adv_img.png
LV_IMG_DECLARE(ui_img_wifi_connecting_png);    // assets/wifi_connecting.png
LV_IMG_DECLARE(ui_img_cloud_connected_png);    // assets/cloud_connected.png
LV_IMG_DECLARE(ui_img_automode_png_png);    // assets/automode_png.png
LV_IMG_DECLARE(ui_img_mode_select_eco_png);    // assets/mode_select_eco.png
LV_IMG_DECLARE(ui_img_mode_select_rapid_png);    // assets/mode_select_rapid.png
LV_IMG_DECLARE(ui_img_wifidisabled1_png);    // assets/WiFiDisabled1.png
LV_IMG_DECLARE(ui_img_mic_listening_png);    // assets/mic_listening.png
LV_IMG_DECLARE(ui_img_incorrect_img_png);    // assets/incorrect_img.png
LV_IMG_DECLARE(ui_img_mode_select_fan_png);    // assets/mode_select_fan.png
LV_IMG_DECLARE(ui_img_undo_png);    // assets/undo.png
LV_IMG_DECLARE(ui_img_149480563);    // assets/cloud-download.png
LV_IMG_DECLARE(ui_img_info_png);    // assets/info.png
LV_IMG_DECLARE(ui_img_icn_home_png);    // assets/icn_home.png
LV_IMG_DECLARE(ui_img_brightness_png);    // assets/brightness.png
LV_IMG_DECLARE(ui_img_mode_select_auto_png);
// LV_IMG_DECLARE(ui_img_temp_arc_bg_2_png); // TODO cleanup unused images

LV_IMG_DECLARE(ui_img_344061264);
LV_IMG_DECLARE(ui_img_bootimg_cmp_png);
LV_IMG_DECLARE(ble_connected_home_icon);
LV_IMG_DECLARE(ui_img_ble_connected_50_png);
LV_IMG_DECLARE(ui_img_mode_select_auto_png);
// LV_IMG_DECLARE(ui_img_background_6_png); // TODO cleanup unused images


// FONTS
LV_FONT_DECLARE(ui_font_Roboto80);
LV_FONT_DECLARE(ui_font_sans14);
LV_FONT_DECLARE(ui_font_sans16);
LV_FONT_DECLARE(ui_font_sans22);
LV_FONT_DECLARE(ui_font_sans24);
LV_FONT_DECLARE(ui_font_sans28);
LV_FONT_DECLARE(ui_font_sans30);
LV_FONT_DECLARE(ui_font_sans32);
LV_FONT_DECLARE(ui_font_sans34);
LV_FONT_DECLARE(ui_font_sans36);

// UI INIT
void ui_init(void);
void ui_destroy(void);
void ui_demo_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
