// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: Thermostat_HMI

#include "ui.h"

lv_obj_t * ui_AboutScreen;
lv_obj_t * ui_Container6;
lv_obj_t * ui_aboutscreenlbl;
lv_obj_t * ui_backgesture2;
lv_obj_t * ui_Label18;
lv_obj_t * ui_Panel13;
lv_obj_t * ui_Panel15;
lv_obj_t * ui_Panel16;
lv_obj_t * ui_Label19;
lv_obj_t * ui_Panel14;
lv_obj_t * ui_homebtnimg2;
lv_obj_t * ui_homebtn2;

// event funtions
void ui_event_backgesture2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_SystemSettings, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 230, 0, &ui_SystemSettings_screen_init);
    }
}

void ui_event_homebtn2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ActiveScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 230, 0, &ui_ActiveScreen_screen_init);
    }
}

// build funtions

void ui_AboutScreen_screen_init(void)
{
    ui_AboutScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_AboutScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AboutScreen, lv_color_hex(0x08665C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AboutScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container6 = lv_obj_create(ui_AboutScreen);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, 475);
    lv_obj_set_height(ui_Container6, 479);
    lv_obj_set_x(ui_Container6, -17);
    lv_obj_set_y(ui_Container6, -2);
    lv_obj_set_align(ui_Container6, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_aboutscreenlbl = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_aboutscreenlbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_aboutscreenlbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_aboutscreenlbl, -19);
    lv_obj_set_y(ui_aboutscreenlbl, -198);
    lv_obj_set_align(ui_aboutscreenlbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_aboutscreenlbl, "About");
    lv_obj_set_style_text_color(ui_aboutscreenlbl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_aboutscreenlbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_aboutscreenlbl, &ui_font_sans36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backgesture2 = lv_button_create(ui_Container6);
    lv_obj_set_width(ui_backgesture2, 460);
    lv_obj_set_height(ui_backgesture2, 467);
    lv_obj_set_x(ui_backgesture2, 0);
    lv_obj_set_y(ui_backgesture2, 2);
    lv_obj_set_align(ui_backgesture2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backgesture2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_backgesture2, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_backgesture2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backgesture2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_backgesture2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_backgesture2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_backgesture2);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, -163);
    lv_obj_set_y(ui_Label18, -135);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "F.W Ver: ");
    lv_obj_add_flag(ui_Label18, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Label18, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label18, &ui_font_sans32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel13 = lv_obj_create(ui_backgesture2);
    lv_obj_set_width(ui_Panel13, 460);
    lv_obj_set_height(ui_Panel13, 3);
    lv_obj_set_x(ui_Panel13, 0);
    lv_obj_set_y(ui_Panel13, -99);
    lv_obj_set_align(ui_Panel13, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel13, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Panel13, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Panel13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel13, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel15 = lv_obj_create(ui_backgesture2);
    lv_obj_set_width(ui_Panel15, 460);
    lv_obj_set_height(ui_Panel15, 3);
    lv_obj_set_x(ui_Panel15, -3);
    lv_obj_set_y(ui_Panel15, 155);
    lv_obj_set_align(ui_Panel15, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel15, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Panel15, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Panel15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel15, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel16 = lv_obj_create(ui_backgesture2);
    lv_obj_set_width(ui_Panel16, 460);
    lv_obj_set_height(ui_Panel16, 3);
    lv_obj_set_x(ui_Panel16, -2);
    lv_obj_set_y(ui_Panel16, -17);
    lv_obj_set_align(ui_Panel16, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel16, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Panel16, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Panel16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel16, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label19 = lv_label_create(ui_backgesture2);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, -65);
    lv_obj_set_y(ui_Label19, -135);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "1.0.0");
    lv_obj_add_flag(ui_Label19, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Label19, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label19, &ui_font_sans32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel14 = lv_obj_create(ui_backgesture2);
    lv_obj_set_width(ui_Panel14, 460);
    lv_obj_set_height(ui_Panel14, 3);
    lv_obj_set_x(ui_Panel14, -2);
    lv_obj_set_y(ui_Panel14, 70);
    lv_obj_set_align(ui_Panel14, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel14, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Panel14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Panel14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_homebtnimg2 = lv_image_create(ui_backgesture2);
    lv_image_set_src(ui_homebtnimg2, &ui_img_344061264);
    lv_obj_set_width(ui_homebtnimg2, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_homebtnimg2, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_homebtnimg2, 179);
    lv_obj_set_y(ui_homebtnimg2, -194);
    lv_obj_set_align(ui_homebtnimg2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_homebtnimg2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_homebtnimg2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_homebtn2 = lv_button_create(ui_backgesture2);
    lv_obj_set_width(ui_homebtn2, 61);
    lv_obj_set_height(ui_homebtn2, 68);
    lv_obj_set_x(ui_homebtn2, 179);
    lv_obj_set_y(ui_homebtn2, -194);
    lv_obj_set_align(ui_homebtn2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_homebtn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_homebtn2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_homebtn2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_homebtn2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_homebtn2, ui_event_homebtn2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_backgesture2, ui_event_backgesture2, LV_EVENT_ALL, NULL);

}

void ui_AboutScreen_screen_destroy(void)
{
    if(ui_AboutScreen) lv_obj_del(ui_AboutScreen);

    // NULL screen variables
    ui_AboutScreen = NULL;
    ui_Container6 = NULL;
    ui_aboutscreenlbl = NULL;
    ui_backgesture2 = NULL;
    ui_Label18 = NULL;
    ui_Panel13 = NULL;
    ui_Panel15 = NULL;
    ui_Panel16 = NULL;
    ui_Label19 = NULL;
    ui_Panel14 = NULL;
    ui_homebtnimg2 = NULL;
    ui_homebtn2 = NULL;

}
