// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Thermostat_HMI

#include "ui.h"
#define bg_color

void ui_ActiveScreen_screen_init(void)
{
    ui_ActiveScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ActiveScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    
    #if defined (bg_color)
    lv_obj_set_style_bg_color(ui_ActiveScreen, lv_color_hex(0x1A1B1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ActiveScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_grad_color(ui_ActiveScreen, lv_color_hex(0x18AB9B), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_main_stop(ui_ActiveScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_grad_stop(ui_ActiveScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_grad_dir(ui_ActiveScreen, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    #else 
    ui_backgroundimage = lv_image_create(ui_ActiveScreen);
    lv_image_set_src(ui_backgroundimage, &ui_img_background_png);
    lv_obj_set_width(ui_backgroundimage, LV_SIZE_CONTENT);   /// 480
    lv_obj_set_height(ui_backgroundimage, LV_SIZE_CONTENT);    /// 480
    lv_obj_set_x(ui_backgroundimage, -16);
    lv_obj_set_y(ui_backgroundimage, 0);
    lv_obj_set_align(ui_backgroundimage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backgroundimage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_backgroundimage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    #endif

    ui_Container1 = lv_obj_create(ui_ActiveScreen);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 475);
    lv_obj_set_height(ui_Container1, 479);
    lv_obj_set_x(ui_Container1, -16);
    lv_obj_set_y(ui_Container1, -1);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    // lv_obj_set_style_border_color(ui_Container1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_border_opa(ui_Container1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_border_width(ui_Container1, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainTempactive = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_MainTempactive, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MainTempactive, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MainTempactive, 7);
    lv_obj_set_y(ui_MainTempactive, -19);
    lv_obj_set_align(ui_MainTempactive, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MainTempactive, "24°c");
    lv_obj_set_style_text_color(ui_MainTempactive, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MainTempactive, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MainTempactive, &ui_font_Roboto80, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeColonactive = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_TimeColonactive, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeColonactive, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeColonactive, -149);
    lv_obj_set_y(ui_TimeColonactive, -170);
    lv_obj_set_align(ui_TimeColonactive, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimeColonactive, ":");
    lv_obj_set_style_text_color(ui_TimeColonactive, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TimeColonactive, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TimeColonactive, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeHactive = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_TimeHactive, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeHactive, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeHactive, -180);
    lv_obj_set_y(ui_TimeHactive, -165);
    lv_obj_set_align(ui_TimeHactive, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimeHactive, "00");
    lv_obj_set_style_text_color(ui_TimeHactive, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TimeHactive, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TimeHactive, &ui_font_sans34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeMactive = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_TimeMactive, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeMactive, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeMactive, -120);
    lv_obj_set_y(ui_TimeMactive, -165);
    lv_obj_set_align(ui_TimeMactive, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimeMactive, "00");
    lv_obj_set_style_text_color(ui_TimeMactive, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TimeMactive, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TimeMactive, &ui_font_sans34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dateactive = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Dateactive, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Dateactive, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dateactive, -143);
    lv_obj_set_y(ui_Dateactive, -204);
    lv_obj_set_align(ui_Dateactive, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Dateactive, "");
    lv_obj_set_style_text_color(ui_Dateactive, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dateactive, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Dateactive, &ui_font_sans30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weathercontainer1 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_weathercontainer1);
    lv_obj_set_width(ui_weathercontainer1, 240);
    lv_obj_set_height(ui_weathercontainer1, 98);
    lv_obj_set_x(ui_weathercontainer1, 120);
    lv_obj_set_y(ui_weathercontainer1, -179);
    lv_obj_set_align(ui_weathercontainer1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_weathercontainer1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_weathercontainer1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WeatherTextactive = lv_label_create(ui_weathercontainer1);
    lv_obj_set_width(ui_WeatherTextactive, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WeatherTextactive, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WeatherTextactive, -43);
    lv_obj_set_y(ui_WeatherTextactive, -23);
    lv_obj_set_align(ui_WeatherTextactive, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WeatherTextactive, "Bengaluru");
    lv_obj_set_style_text_color(ui_WeatherTextactive, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WeatherTextactive, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WeatherTextactive, &ui_font_sans28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_container1text = lv_label_create(ui_weathercontainer1);
    lv_obj_set_width(ui_container1text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_container1text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_container1text, -80);
    lv_obj_set_y(ui_container1text, 11);
    lv_obj_set_align(ui_container1text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_container1text, "28°c");
    lv_obj_set_style_text_color(ui_container1text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_container1text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_container1text, &ui_font_sans24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_image_create(ui_weathercontainer1);
    lv_image_set_src(ui_Image3, &ui_img_cloudy_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 60
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 60
    lv_obj_set_x(ui_Image3, 69);
    lv_obj_set_y(ui_Image3, -7);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_humidity = lv_label_create(ui_weathercontainer1);
    lv_obj_set_width(ui_humidity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humidity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humidity, -16);
    lv_obj_set_y(ui_humidity, 11);
    lv_obj_set_align(ui_humidity, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humidity, "Sunny");
    lv_obj_set_style_text_color(ui_humidity, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_humidity, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_humidity, &ui_font_sans24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weathercontainer2 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_weathercontainer2);
    lv_obj_set_width(ui_weathercontainer2, 239);
    lv_obj_set_height(ui_weathercontainer2, 98);
    lv_obj_set_x(ui_weathercontainer2, 119);
    lv_obj_set_y(ui_weathercontainer2, -178);
    lv_obj_set_align(ui_weathercontainer2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_weathercontainer2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WeatherTextactive2 = lv_label_create(ui_weathercontainer2);
    lv_obj_set_width(ui_WeatherTextactive2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WeatherTextactive2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WeatherTextactive2, -44);
    lv_obj_set_y(ui_WeatherTextactive2, -25);
    lv_obj_set_align(ui_WeatherTextactive2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WeatherTextactive2, "Bengaluru");
    lv_obj_set_style_text_color(ui_WeatherTextactive2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WeatherTextactive2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WeatherTextactive2, &ui_font_sans28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_container2text = lv_label_create(ui_weathercontainer2);
    lv_obj_set_width(ui_container2text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_container2text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_container2text, -87);
    lv_obj_set_y(ui_container2text, 10);
    lv_obj_set_align(ui_container2text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_container2text, "28°c");
    lv_obj_set_style_text_color(ui_container2text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_container2text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_container2text, &ui_font_sans24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humidity2 = lv_label_create(ui_weathercontainer2);
    lv_obj_set_width(ui_humidity2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humidity2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humidity2, -19);
    lv_obj_set_y(ui_humidity2, 11);
    lv_obj_set_align(ui_humidity2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humidity2, "Cloudy");
    lv_obj_set_style_text_color(ui_humidity2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_humidity2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_humidity2, &ui_font_sans24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weatheractive2 = lv_image_create(ui_weathercontainer2);
    lv_image_set_src(ui_weatheractive2, &ui_img_sun_png);
    lv_obj_set_width(ui_weatheractive2, LV_SIZE_CONTENT);   /// 70
    lv_obj_set_height(ui_weatheractive2, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_weatheractive2, 65);
    lv_obj_set_y(ui_weatheractive2, -12);
    lv_obj_set_align(ui_weatheractive2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_weatheractive2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_weatheractive2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_weathercontainer3 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_weathercontainer3);
    lv_obj_set_width(ui_weathercontainer3, 252);
    lv_obj_set_height(ui_weathercontainer3, 98);
    lv_obj_set_x(ui_weathercontainer3, 119);
    lv_obj_set_y(ui_weathercontainer3, -178);
    lv_obj_set_align(ui_weathercontainer3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_weathercontainer3, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_weathercontainer3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WeatherTextactive3 = lv_label_create(ui_weathercontainer3);
    lv_obj_set_width(ui_WeatherTextactive3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WeatherTextactive3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WeatherTextactive3, -48);
    lv_obj_set_y(ui_WeatherTextactive3, -25);
    lv_obj_set_align(ui_WeatherTextactive3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WeatherTextactive3, "Bengaluru");
    lv_obj_set_style_text_color(ui_WeatherTextactive3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WeatherTextactive3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WeatherTextactive3, &ui_font_sans28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humidity3 = lv_label_create(ui_weathercontainer3);
    lv_obj_set_width(ui_humidity3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humidity3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humidity3, -20);
    lv_obj_set_y(ui_humidity3, 9);
    lv_obj_set_align(ui_humidity3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humidity3, "Showers");
    lv_obj_set_style_text_color(ui_humidity3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_humidity3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_humidity3, &ui_font_sans22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_container3text = lv_label_create(ui_weathercontainer3);
    lv_obj_set_width(ui_container3text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_container3text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_container3text, -92);
    lv_obj_set_y(ui_container3text, 8);
    lv_obj_set_align(ui_container3text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_container3text, "24°c");
    lv_obj_set_style_text_color(ui_container3text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_container3text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_container3text, &ui_font_sans24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_image_create(ui_weathercontainer3);
    lv_image_set_src(ui_Image5, &ui_img_rain_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 55
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 55
    lv_obj_set_x(ui_Image5, 68);
    lv_obj_set_y(ui_Image5, -9);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RoomTempactive = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_RoomTempactive, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RoomTempactive, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RoomTempactive, -161);
    lv_obj_set_y(ui_RoomTempactive, 54);
    lv_obj_set_align(ui_RoomTempactive, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RoomTempactive, "18°c");
    lv_obj_set_style_text_color(ui_RoomTempactive, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RoomTempactive, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RoomTempactive, &ui_font_sans36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_swiperightgesture = lv_button_create(ui_Container1);
    lv_obj_set_width(ui_swiperightgesture, 458);
    lv_obj_set_height(ui_swiperightgesture, 400);
    lv_obj_set_x(ui_swiperightgesture, 0);
    lv_obj_set_y(ui_swiperightgesture, 28);
    lv_obj_set_align(ui_swiperightgesture, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_swiperightgesture, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_swiperightgesture, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_swiperightgesture, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_swiperightgesture, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_swiperightgesture, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_swiperightgesture, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Roomtextactive = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Roomtextactive, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Roomtextactive, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Roomtextactive, -160);
    lv_obj_set_y(ui_Roomtextactive, -33);
    lv_obj_set_align(ui_Roomtextactive, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Roomtextactive, "Kitchen");
    lv_obj_set_style_text_color(ui_Roomtextactive, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Roomtextactive, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Roomtextactive, &ui_font_sans30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_changeroomgesture = lv_button_create(ui_Container1);
    lv_obj_set_width(ui_changeroomgesture, 123);
    lv_obj_set_height(ui_changeroomgesture, 130);
    lv_obj_set_x(ui_changeroomgesture, -158);
    lv_obj_set_y(ui_changeroomgesture, -32);
    lv_obj_set_align(ui_changeroomgesture, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_changeroomgesture, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags
    lv_obj_set_style_bg_color(ui_changeroomgesture, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_changeroomgesture, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_changeroomgesture, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_changeroomgesture, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_smalluparrow = lv_image_create(ui_Container1);
    lv_image_set_src(ui_smalluparrow, &ui_img_209868359);
    lv_obj_set_width(ui_smalluparrow, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_smalluparrow, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_smalluparrow, -166);
    lv_obj_set_y(ui_smalluparrow, -76);
    lv_obj_set_align(ui_smalluparrow, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_smalluparrow, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_smalluparrow, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bigdownarrow = lv_image_create(ui_Container1);
    lv_image_set_src(ui_bigdownarrow, &ui_img_614296446);
    lv_obj_set_width(ui_bigdownarrow, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_bigdownarrow, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_bigdownarrow, 0);
    lv_obj_set_y(ui_bigdownarrow, 48);
    lv_obj_set_align(ui_bigdownarrow, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bigdownarrow, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_bigdownarrow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_rotation(ui_bigdownarrow, 1800);

    ui_Mainroomtextactive = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Mainroomtextactive, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Mainroomtextactive, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Mainroomtextactive, 7);
    lv_obj_set_y(ui_Mainroomtextactive, 104);
    lv_obj_set_align(ui_Mainroomtextactive, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Mainroomtextactive, "Living Room");
    lv_obj_set_style_text_color(ui_Mainroomtextactive, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Mainroomtextactive, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Mainroomtextactive, &ui_font_sans32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_eco = lv_image_create(ui_Container1);
    lv_image_set_src(ui_eco, &ui_img_eco_png);
    lv_obj_set_width(ui_eco, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_eco, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_eco, 8);
    lv_obj_set_y(ui_eco, 187);
    lv_obj_set_align(ui_eco, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_eco, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_eco, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_settings = lv_image_create(ui_Container1);
    lv_image_set_src(ui_settings, &ui_img_settings_png);
    lv_obj_set_width(ui_settings, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_settings, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_settings, -152);
    lv_obj_set_y(ui_settings, 187);
    lv_obj_set_align(ui_settings, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_settings, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TempIncbutton = lv_button_create(ui_Container1);
    lv_obj_set_width(ui_TempIncbutton, 76);
    lv_obj_set_height(ui_TempIncbutton, 54);
    lv_obj_set_x(ui_TempIncbutton, 3);
    lv_obj_set_y(ui_TempIncbutton, -98);
    lv_obj_set_align(ui_TempIncbutton, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_TempIncbutton, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TempIncbutton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempIncbutton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TempIncbutton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TempIncbutton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_TempIncbutton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_TempIncbutton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempDecbutton = lv_button_create(ui_Container1);
    lv_obj_set_width(ui_TempDecbutton, 76);
    lv_obj_set_height(ui_TempDecbutton, 52);
    lv_obj_set_x(ui_TempDecbutton, 2);
    lv_obj_set_y(ui_TempDecbutton, 48);
    lv_obj_set_align(ui_TempDecbutton, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_TempDecbutton, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TempDecbutton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempDecbutton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TempDecbutton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TempDecbutton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_TempDecbutton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_TempDecbutton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_biguparrow = lv_image_create(ui_Container1);
    lv_image_set_src(ui_biguparrow, &ui_img_614296446);
    lv_obj_set_width(ui_biguparrow, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_biguparrow, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_biguparrow, 2);
    lv_obj_set_y(ui_biguparrow, -99);
    lv_obj_set_align(ui_biguparrow, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_biguparrow, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_gesturebutton = lv_button_create(ui_Container1);
    lv_obj_set_width(ui_gesturebutton, 173);
    lv_obj_set_height(ui_gesturebutton, 108);
    lv_obj_set_x(ui_gesturebutton, 6);
    lv_obj_set_y(ui_gesturebutton, -25);
    lv_obj_set_align(ui_gesturebutton, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_gesturebutton, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags
    lv_obj_set_style_bg_color(ui_gesturebutton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_gesturebutton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_gesturebutton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_gesturebutton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifi = lv_image_create(ui_Container1);
    lv_image_set_src(ui_wifi, &ui_img_wifi_png);
    lv_obj_set_width(ui_wifi, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_wifi, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_wifi, 163);
    lv_obj_set_y(ui_wifi, 186);
    lv_obj_set_align(ui_wifi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifi, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_wifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_smalldownarrow = lv_image_create(ui_Container1);
    lv_image_set_src(ui_smalldownarrow, &ui_img_209868359);
    lv_obj_set_width(ui_smalldownarrow, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_smalldownarrow, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_smalldownarrow, -167);
    lv_obj_set_y(ui_smalldownarrow, 7);
    lv_obj_set_align(ui_smalldownarrow, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_smalldownarrow, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_smalldownarrow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_rotation(ui_smalldownarrow, 1800);

    ui_changeroomup = lv_button_create(ui_Container1);
    lv_obj_set_width(ui_changeroomup, 56);
    lv_obj_set_height(ui_changeroomup, 47);
    lv_obj_set_x(ui_changeroomup, -166);
    lv_obj_set_y(ui_changeroomup, -78);
    lv_obj_set_align(ui_changeroomup, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_changeroomup, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags
    lv_obj_set_style_bg_color(ui_changeroomup, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_changeroomup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_changeroomup, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_changeroomup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_changeroomup, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_changeroomup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_changeroomdown = lv_button_create(ui_Container1);
    lv_obj_set_width(ui_changeroomdown, 55);
    lv_obj_set_height(ui_changeroomdown, 44);
    lv_obj_set_x(ui_changeroomdown, -166);
    lv_obj_set_y(ui_changeroomdown, 10);
    lv_obj_set_align(ui_changeroomdown, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_changeroomdown, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags
    lv_obj_set_style_bg_color(ui_changeroomdown, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_changeroomdown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_changeroomdown, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_changeroomdown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_changeroomdown, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_changeroomdown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fanbutton = lv_button_create(ui_Container1);
    lv_obj_set_width(ui_fanbutton, 82);
    lv_obj_set_height(ui_fanbutton, 116);
    lv_obj_set_x(ui_fanbutton, 174);
    lv_obj_set_y(ui_fanbutton, -18);
    lv_obj_set_align(ui_fanbutton, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_fanbutton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fanbutton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_fanbutton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_fanbutton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fanactive = lv_image_create(ui_fanbutton);
    lv_image_set_src(ui_fanactive, &ui_img_fanactive_png);
    lv_obj_set_width(ui_fanactive, LV_SIZE_CONTENT);   /// 75
    lv_obj_set_height(ui_fanactive, LV_SIZE_CONTENT);    /// 75
    lv_obj_set_x(ui_fanactive, 3);
    lv_obj_set_y(ui_fanactive, 2);
    lv_obj_set_align(ui_fanactive, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_fanactive, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_fanactive, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bluecontainer = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_bluecontainer);
    lv_obj_set_width(ui_bluecontainer, 56);
    lv_obj_set_height(ui_bluecontainer, 130);
    lv_obj_set_x(ui_bluecontainer, 172);
    lv_obj_set_y(ui_bluecontainer, -18);
    lv_obj_set_align(ui_bluecontainer, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bluecontainer, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_bluecontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_blue1 = lv_image_create(ui_bluecontainer);
    lv_image_set_src(ui_blue1, &ui_img_picture5_png);
    lv_obj_set_width(ui_blue1, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_blue1, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_blue1, 6);
    lv_obj_set_y(ui_blue1, -41);
    lv_obj_set_align(ui_blue1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_blue1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_blue1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_blue3 = lv_image_create(ui_bluecontainer);
    lv_image_set_src(ui_blue3, &ui_img_picture8_png);
    lv_obj_set_width(ui_blue3, LV_SIZE_CONTENT);   /// 25
    lv_obj_set_height(ui_blue3, LV_SIZE_CONTENT);    /// 15
    lv_obj_set_x(ui_blue3, 6);
    lv_obj_set_y(ui_blue3, 16);
    lv_obj_set_align(ui_blue3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_blue3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_blue3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_blue4 = lv_image_create(ui_bluecontainer);
    lv_image_set_src(ui_blue4, &ui_img_picture7_png);
    lv_obj_set_width(ui_blue4, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_blue4, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_blue4, 7);
    lv_obj_set_y(ui_blue4, 39);
    lv_obj_set_align(ui_blue4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_blue4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_blue4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_blue2 = lv_image_create(ui_bluecontainer);
    lv_image_set_src(ui_blue2, &ui_img_picture6_png);
    lv_obj_set_width(ui_blue2, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_blue2, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_blue2, 6);
    lv_obj_set_y(ui_blue2, -9);
    lv_obj_set_align(ui_blue2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_blue2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_blue2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_redcontainer = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_redcontainer);
    lv_obj_set_width(ui_redcontainer, 68);
    lv_obj_set_height(ui_redcontainer, 131);
    lv_obj_set_x(ui_redcontainer, 172);
    lv_obj_set_y(ui_redcontainer, -37);
    lv_obj_set_align(ui_redcontainer, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_redcontainer, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_redcontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_red1 = lv_image_create(ui_redcontainer);
    lv_image_set_src(ui_red1, &ui_img_picture1_png);
    lv_obj_set_width(ui_red1, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_red1, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_red1, 7);
    lv_obj_set_y(ui_red1, -27);
    lv_obj_set_align(ui_red1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_red1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_red1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_red2 = lv_image_create(ui_redcontainer);
    lv_image_set_src(ui_red2, &ui_img_picture2_png);
    lv_obj_set_width(ui_red2, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_red2, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_red2, 6);
    lv_obj_set_y(ui_red2, 7);
    lv_obj_set_align(ui_red2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_red2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_red2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_red3 = lv_image_create(ui_redcontainer);
    lv_image_set_src(ui_red3, &ui_img_picture4_png);
    lv_obj_set_width(ui_red3, LV_SIZE_CONTENT);   /// 25
    lv_obj_set_height(ui_red3, LV_SIZE_CONTENT);    /// 15
    lv_obj_set_x(ui_red3, 6);
    lv_obj_set_y(ui_red3, 36);
    lv_obj_set_align(ui_red3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_red3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_red3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_red4 = lv_image_create(ui_redcontainer);
    lv_image_set_src(ui_red4, &ui_img_picture3_png);
    lv_obj_set_width(ui_red4, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_red4, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_red4, 6);
    lv_obj_set_y(ui_red4, 59);
    lv_obj_set_align(ui_red4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_red4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_red4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_changescreenbuttonACT = lv_button_create(ui_ActiveScreen);
    lv_obj_set_width(ui_changescreenbuttonACT, 180);
    lv_obj_set_height(ui_changescreenbuttonACT, 84);
    lv_obj_set_x(ui_changescreenbuttonACT, -133);
    lv_obj_set_y(ui_changescreenbuttonACT, -177);
    lv_obj_set_align(ui_changescreenbuttonACT, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_changescreenbuttonACT, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_changescreenbuttonACT, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_changescreenbuttonACT, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_changescreenbuttonACT, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_changescreenbuttonACT, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_changescreenbuttonACT, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Settingsbutton = lv_button_create(ui_ActiveScreen);
    lv_obj_set_width(ui_Settingsbutton, 74);
    lv_obj_set_height(ui_Settingsbutton, 82);
    lv_obj_set_x(ui_Settingsbutton, -166);
    lv_obj_set_y(ui_Settingsbutton, 185);
    lv_obj_set_align(ui_Settingsbutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Settingsbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Settingsbutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Settingsbutton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Settingsbutton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Settingsbutton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Settingsbutton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_currenttemp = lv_label_create(ui_ActiveScreen);
    lv_obj_set_width(ui_currenttemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_currenttemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_currenttemp, 163);
    lv_obj_set_y(ui_currenttemp, -114);
    lv_obj_set_align(ui_currenttemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_currenttemp, "24°c");
    lv_obj_add_flag(ui_currenttemp, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_currenttemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_currenttemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_currenttemp, &ui_font_sans28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fanspeedcontainer = lv_obj_create(ui_ActiveScreen);
    lv_obj_remove_style_all(ui_fanspeedcontainer);
    lv_obj_set_width(ui_fanspeedcontainer, 58);
    lv_obj_set_height(ui_fanspeedcontainer, 219);
    lv_obj_set_x(ui_fanspeedcontainer, 163);
    lv_obj_set_y(ui_fanspeedcontainer, -43);
    lv_obj_set_align(ui_fanspeedcontainer, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_fanspeedcontainer, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_fanspeedcontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_highbutton = lv_button_create(ui_fanspeedcontainer);
    lv_obj_set_width(ui_highbutton, 21);
    lv_obj_set_height(ui_highbutton, 75);
    lv_obj_set_x(ui_highbutton, -1);
    lv_obj_set_y(ui_highbutton, -69);
    lv_obj_set_align(ui_highbutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_highbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_highbutton, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_highbutton, lv_color_hex(0xD1D1D1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_highbutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_highbutton);
    lv_obj_set_width(ui_Label2, 11);
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -1);
    lv_obj_set_y(ui_Label2, 0);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "HIGH");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x040404), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &ui_font_sans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_medbutton = lv_button_create(ui_fanspeedcontainer);
    lv_obj_set_width(ui_medbutton, 21);
    lv_obj_set_height(ui_medbutton, 67);
    lv_obj_set_x(ui_medbutton, -1);
    lv_obj_set_y(ui_medbutton, -3);
    lv_obj_set_align(ui_medbutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_medbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_medbutton, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_medbutton, lv_color_hex(0xC9C9C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_medbutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_medbutton);
    lv_obj_set_width(ui_Label9, 13);
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -1);
    lv_obj_set_y(ui_Label9, 1);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "MED");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0x040404), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label9, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &ui_font_sans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lowbutton = lv_button_create(ui_fanspeedcontainer);
    lv_obj_set_width(ui_lowbutton, 21);
    lv_obj_set_height(ui_lowbutton, 68);
    lv_obj_set_x(ui_lowbutton, -1);
    lv_obj_set_y(ui_lowbutton, 63);
    lv_obj_set_align(ui_lowbutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_lowbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_lowbutton, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_lowbutton, lv_color_hex(0xD1D1D1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lowbutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_lowbutton);
    lv_obj_set_width(ui_Label10, 13);
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -12);
    lv_obj_set_y(ui_Label10, -3);
    lv_label_set_text(ui_Label10, "LOW");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0x040404), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label10, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &ui_font_sans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_button_create(ui_ActiveScreen);
    lv_obj_set_width(ui_Button3, 100);
    lv_obj_set_height(ui_Button3, 64);
    lv_obj_set_x(ui_Button3, 148);
    lv_obj_set_y(ui_Button3, 183);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button4 = lv_button_create(ui_ActiveScreen);
    lv_obj_set_width(ui_Button4, 100);
    lv_obj_set_height(ui_Button4, 64);
    lv_obj_set_x(ui_Button4, -9);
    lv_obj_set_y(ui_Button4, 184);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weatherbutton = lv_button_create(ui_ActiveScreen);
    lv_obj_set_width(ui_weatherbutton, 239);
    lv_obj_set_height(ui_weatherbutton, 92);
    lv_obj_set_x(ui_weatherbutton, 92);
    lv_obj_set_y(ui_weatherbutton, -180);
    lv_obj_set_align(ui_weatherbutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_weatherbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_weatherbutton, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_weatherbutton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_weatherbutton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_weatherbutton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_weatherbutton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_swiperightgesture, ui_event_swiperightgesture, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_changeroomgesture, ui_event_changeroomgesture, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TempIncbutton, ui_event_TempIncbutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TempDecbutton, ui_event_TempDecbutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_gesturebutton, ui_event_gesturebutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_changeroomup, ui_event_changeroomup, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_changeroomdown, ui_event_changeroomdown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_fanbutton, ui_event_fanbutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_changescreenbuttonACT, ui_event_changescreenbuttonACT, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Settingsbutton, ui_event_Settingsbutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_highbutton, ui_event_highbutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_medbutton, ui_event_medbutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_lowbutton, ui_event_lowbutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_weatherbutton, ui_event_weatherbutton, LV_EVENT_ALL, NULL);

}
