// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: SettingsScreen_HMI

#include "ui.h"

lv_obj_t * ui_DateTimeSettings;
lv_obj_t * ui_datetimecontainer;
lv_obj_t * ui_dateandtimesettinglbl;
lv_obj_t * ui_dateandtimesetting;
lv_obj_t * ui_dtPanel25;
lv_obj_t * ui_dthomebtnimg5;
lv_obj_t * ui_dthomebtn5;
lv_obj_t * ui_Date;
lv_obj_t * ui_datetimetextarea;
lv_obj_t * ui_dtTime;
lv_obj_t * ui_thinc;
lv_obj_t * ui_tminc;
lv_obj_t * ui_tsinc;
lv_obj_t * ui_thdec;
lv_obj_t * ui_tmdec;
lv_obj_t * ui_tsdec;
lv_obj_t * ui_dtcol1;
lv_obj_t * ui_dtcol2;
lv_obj_t * ui_dttimeupdtebtn;
lv_obj_t * ui_dtupdatebtnlbl;
lv_obj_t * ui_htext;
lv_obj_t * ui_mtext;
lv_obj_t * ui_stext;
lv_obj_t * ui_dtCalendar;

// event funtions
void ui_event_dateandtimesetting(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_SystemSettings, LV_SCR_LOAD_ANIM_FADE_IN, 30, 0, &ui_SystemSettings_screen_init);
    }
}

void ui_event_dthomebtn5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ActiveScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 30, 0, &ui_ActiveScreen_screen_init);
    }
}

void ui_event_datetimetextarea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_dtCalendar, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_opacity_set(ui_dateandtimesetting, 100);
    }
}

void ui_event_thinc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        inc_thour(e);
    }
}

void ui_event_tminc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        inc_tmin(e);
    }
}

void ui_event_tsinc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        inc_tsec(e);
    }
}

void ui_event_thdec(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        dec_thour(e);
    }
}

void ui_event_tmdec(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        dec_tmin(e);
    }
}

void ui_event_tsdec(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        dec_tsec(e);
    }
}

void ui_event_dttimeupdtebtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        update_date_time_rtc(e);
    }
}

void ui_event_dtCalendar(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_flag_modify(ui_dtCalendar, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_opacity_set(ui_dateandtimesetting, 255);
        update_calendar_date(e);
    }
}

// build funtions

void ui_DateTimeSettings_screen_init(void)
{
    ui_DateTimeSettings = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_DateTimeSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DateTimeSettings, lv_color_hex(0x06534B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DateTimeSettings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_datetimecontainer = lv_obj_create(ui_DateTimeSettings);
    lv_obj_remove_style_all(ui_datetimecontainer);
    lv_obj_set_width(ui_datetimecontainer, 475);
    lv_obj_set_height(ui_datetimecontainer, 479);
    lv_obj_set_x(ui_datetimecontainer, -17);
    lv_obj_set_y(ui_datetimecontainer, -2);
    lv_obj_set_align(ui_datetimecontainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_datetimecontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_dateandtimesettinglbl = lv_label_create(ui_datetimecontainer);
    lv_obj_set_width(ui_dateandtimesettinglbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dateandtimesettinglbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dateandtimesettinglbl, -19);
    lv_obj_set_y(ui_dateandtimesettinglbl, -198);
    lv_obj_set_align(ui_dateandtimesettinglbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dateandtimesettinglbl, "Date & Time Settings");
    lv_obj_set_style_text_color(ui_dateandtimesettinglbl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dateandtimesettinglbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dateandtimesettinglbl, &ui_font_sans36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dateandtimesetting = lv_button_create(ui_datetimecontainer);
    lv_obj_set_width(ui_dateandtimesetting, 460);
    lv_obj_set_height(ui_dateandtimesetting, 467);
    lv_obj_set_x(ui_dateandtimesetting, 0);
    lv_obj_set_y(ui_dateandtimesetting, 2);
    lv_obj_set_align(ui_dateandtimesetting, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dateandtimesetting, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_dateandtimesetting, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_dateandtimesetting, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dateandtimesetting, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_dateandtimesetting, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_dateandtimesetting, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dtPanel25 = lv_obj_create(ui_dateandtimesetting);
    lv_obj_set_width(ui_dtPanel25, 460);
    lv_obj_set_height(ui_dtPanel25, 3);
    lv_obj_set_x(ui_dtPanel25, 0);
    lv_obj_set_y(ui_dtPanel25, -97);
    lv_obj_set_align(ui_dtPanel25, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_dtPanel25, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_dtPanel25, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dtPanel25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_dtPanel25, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_dtPanel25, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_dtPanel25, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_dtPanel25, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_dtPanel25, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dthomebtnimg5 = lv_image_create(ui_dateandtimesetting);
    lv_image_set_src(ui_dthomebtnimg5, &ui_img_344061264);
    lv_obj_set_width(ui_dthomebtnimg5, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_dthomebtnimg5, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_dthomebtnimg5, 179);
    lv_obj_set_y(ui_dthomebtnimg5, -194);
    lv_obj_set_align(ui_dthomebtnimg5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dthomebtnimg5, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_dthomebtnimg5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_dthomebtn5 = lv_button_create(ui_dateandtimesetting);
    lv_obj_set_width(ui_dthomebtn5, 61);
    lv_obj_set_height(ui_dthomebtn5, 68);
    lv_obj_set_x(ui_dthomebtn5, 179);
    lv_obj_set_y(ui_dthomebtn5, -194);
    lv_obj_set_align(ui_dthomebtn5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dthomebtn5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_dthomebtn5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_dthomebtn5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dthomebtn5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Date = lv_label_create(ui_dateandtimesetting);
    lv_obj_set_width(ui_Date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Date, -191);
    lv_obj_set_y(ui_Date, -129);
    lv_obj_set_align(ui_Date, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Date, "Date");
    lv_obj_set_style_text_font(ui_Date, &ui_font_sans24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_datetimetextarea = lv_textarea_create(ui_dateandtimesetting);
    lv_obj_set_width(ui_datetimetextarea, 138);
    lv_obj_set_height(ui_datetimetextarea, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_datetimetextarea, -65);
    lv_obj_set_y(ui_datetimetextarea, -132);
    lv_obj_set_align(ui_datetimetextarea, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_datetimetextarea, "10/10/2025");
    lv_textarea_set_placeholder_text(ui_datetimetextarea, "Placeholder...");
    lv_textarea_set_one_line(ui_datetimetextarea, true);
    lv_obj_set_style_text_align(ui_datetimetextarea, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_datetimetextarea, &ui_font_sans22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dtTime = lv_label_create(ui_dateandtimesetting);
    lv_obj_set_width(ui_dtTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dtTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dtTime, -191);
    lv_obj_set_y(ui_dtTime, -41);
    lv_obj_set_align(ui_dtTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dtTime, "Time");
    lv_obj_set_style_text_font(ui_dtTime, &ui_font_sans24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_thinc = lv_image_create(ui_dateandtimesetting);
    lv_image_set_src(ui_thinc, &ui_img_209868359);
    lv_obj_set_width(ui_thinc, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_thinc, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_thinc, -122);
    lv_obj_set_y(ui_thinc, -70);
    lv_obj_set_align(ui_thinc, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_thinc, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_thinc, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_tminc = lv_image_create(ui_dateandtimesetting);
    lv_image_set_src(ui_tminc, &ui_img_209868359);
    lv_obj_set_width(ui_tminc, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tminc, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tminc, -67);
    lv_obj_set_y(ui_tminc, -70);
    lv_obj_set_align(ui_tminc, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_tminc, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_tminc, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_tsinc = lv_image_create(ui_dateandtimesetting);
    lv_image_set_src(ui_tsinc, &ui_img_209868359);
    lv_obj_set_width(ui_tsinc, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tsinc, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tsinc, -14);
    lv_obj_set_y(ui_tsinc, -71);
    lv_obj_set_align(ui_tsinc, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_tsinc, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_tsinc, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_thdec = lv_image_create(ui_dateandtimesetting);
    lv_image_set_src(ui_thdec, &downarrow);
    lv_obj_set_width(ui_thdec, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_thdec, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_thdec, -121);
    lv_obj_set_y(ui_thdec, -5);
    lv_obj_set_align(ui_thdec, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_thdec, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_thdec, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_tmdec = lv_image_create(ui_dateandtimesetting);
    lv_image_set_src(ui_tmdec, &downarrow);
    lv_obj_set_width(ui_tmdec, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tmdec, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tmdec, -67);
    lv_obj_set_y(ui_tmdec, -5);
    lv_obj_set_align(ui_tmdec, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_tmdec, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_tmdec, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_tsdec = lv_image_create(ui_dateandtimesetting);
    lv_image_set_src(ui_tsdec, &downarrow);
    lv_obj_set_width(ui_tsdec, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tsdec, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tsdec, -12);
    lv_obj_set_y(ui_tsdec, -5);
    lv_obj_set_align(ui_tsdec, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_tsdec, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_tsdec, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_dtcol1 = lv_label_create(ui_dateandtimesetting);
    lv_obj_set_width(ui_dtcol1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dtcol1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dtcol1, -94);
    lv_obj_set_y(ui_dtcol1, -35);
    lv_obj_set_align(ui_dtcol1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dtcol1, ":");
    lv_obj_set_style_text_font(ui_dtcol1, &ui_font_sans28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dtcol2 = lv_label_create(ui_dateandtimesetting);
    lv_obj_set_width(ui_dtcol2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dtcol2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dtcol2, -40);
    lv_obj_set_y(ui_dtcol2, -35);
    lv_obj_set_align(ui_dtcol2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dtcol2, ":");
    lv_obj_set_style_text_font(ui_dtcol2, &ui_font_sans28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dttimeupdtebtn = lv_button_create(ui_dateandtimesetting);
    lv_obj_set_width(ui_dttimeupdtebtn, 116);
    lv_obj_set_height(ui_dttimeupdtebtn, 50);
    lv_obj_set_x(ui_dttimeupdtebtn, 141);
    lv_obj_set_y(ui_dttimeupdtebtn, -36);
    lv_obj_set_align(ui_dttimeupdtebtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dttimeupdtebtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_dttimeupdtebtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_dttimeupdtebtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dttimeupdtebtn, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dttimeupdtebtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_dttimeupdtebtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_dttimeupdtebtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_dttimeupdtebtn, lv_color_hex(0x050505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dttimeupdtebtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_dttimeupdtebtn, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dttimeupdtebtn, &ui_font_sans22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dtupdatebtnlbl = lv_label_create(ui_dttimeupdtebtn);
    lv_obj_set_width(ui_dtupdatebtnlbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dtupdatebtnlbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_dtupdatebtnlbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dtupdatebtnlbl, "Update");

    ui_htext = lv_label_create(ui_dateandtimesetting);
    lv_obj_set_width(ui_htext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_htext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_htext, -123);
    lv_obj_set_y(ui_htext, -38);
    lv_obj_set_align(ui_htext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_htext, "13");
    lv_obj_set_style_text_color(ui_htext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_htext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_htext, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_htext, &ui_font_sans24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mtext = lv_label_create(ui_dateandtimesetting);
    lv_obj_set_width(ui_mtext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mtext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_mtext, -67);
    lv_obj_set_y(ui_mtext, -38);
    lv_obj_set_align(ui_mtext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_mtext, "0");
    lv_obj_set_style_text_color(ui_mtext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_mtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_mtext, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_mtext, &ui_font_sans24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_stext = lv_label_create(ui_dateandtimesetting);
    lv_obj_set_width(ui_stext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_stext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_stext, -14);
    lv_obj_set_y(ui_stext, -38);
    lv_obj_set_align(ui_stext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_stext, "0");
    lv_obj_set_style_text_color(ui_stext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_stext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_stext, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_stext, &ui_font_sans24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dtCalendar = lv_calendar_create(ui_datetimecontainer);
    lv_obj_t * ui_dtCalendar_header = lv_calendar_header_arrow_create(ui_dtCalendar);
    lv_obj_set_width(ui_dtCalendar, 335);
    lv_obj_set_height(ui_dtCalendar, 258);
    lv_obj_set_x(ui_dtCalendar, 12);
    lv_obj_set_y(ui_dtCalendar, 33);
    lv_obj_set_align(ui_dtCalendar, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dtCalendar, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_calendar_set_showed_date(ui_dtCalendar, 2025, 9);

    lv_obj_add_event_cb(ui_dthomebtn5, ui_event_dthomebtn5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_datetimetextarea, ui_event_datetimetextarea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_thinc, ui_event_thinc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_tminc, ui_event_tminc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_tsinc, ui_event_tsinc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_thdec, ui_event_thdec, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_tmdec, ui_event_tmdec, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_tsdec, ui_event_tsdec, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_dttimeupdtebtn, ui_event_dttimeupdtebtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_dateandtimesetting, ui_event_dateandtimesetting, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_dtCalendar, ui_event_dtCalendar, LV_EVENT_ALL, NULL);

}

void ui_DateTimeSettings_screen_destroy(void)
{
    if(ui_DateTimeSettings) lv_obj_del(ui_DateTimeSettings);

    // NULL screen variables
    ui_DateTimeSettings = NULL;
    ui_datetimecontainer = NULL;
    ui_dateandtimesettinglbl = NULL;
    ui_dateandtimesetting = NULL;
    ui_dtPanel25 = NULL;
    ui_dthomebtnimg5 = NULL;
    ui_dthomebtn5 = NULL;
    ui_Date = NULL;
    ui_datetimetextarea = NULL;
    ui_dtTime = NULL;
    ui_thinc = NULL;
    ui_tminc = NULL;
    ui_tsinc = NULL;
    ui_thdec = NULL;
    ui_tmdec = NULL;
    ui_tsdec = NULL;
    ui_dtcol1 = NULL;
    ui_dtcol2 = NULL;
    ui_dttimeupdtebtn = NULL;
    ui_dtupdatebtnlbl = NULL;
    ui_htext = NULL;
    ui_mtext = NULL;
    ui_stext = NULL;
    ui_dtCalendar = NULL;

}
