// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Thermostat_HMI

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H
#include "ui.h"
#ifdef __cplusplus
extern "C" {
#endif

void change_room(lv_event_t * e);
void increase_temp(lv_event_t * e);
void decrease_temp(lv_event_t * e);
void weather_change(lv_event_t * e);
void weatherup(lv_event_t * e);
void weatherdown(lv_event_t * e);
void change_brightness(lv_event_t * e);
void increase_temp_step (lv_timer_t * timer);
void decrease_temp_step (lv_timer_t * timer);
void change_fan_speed(lv_event_t * e);
void fan_high(lv_event_t * e);
void fan_med(lv_event_t * e);
void fan_low(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
