// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Thermostat_HMI

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void fan_clicked(lv_event_t * e);
void toggle_mode(lv_event_t * e);
void mic_icon_click_handler(lv_event_t * e);
void hide_mapp_info_label(lv_event_t * e);
void start_ble_adv(lv_event_t * e);
void start_wifi_settings_ilabel_timer(lv_event_t * e);
void connect_wifi(lv_event_t * e);
void display_qrcode(lv_event_t * e);
void delete_wifi_cred(lv_event_t * e);
void open_notifcaiton(lv_event_t * e);
void change_brightness(lv_event_t * e);
void change_idle_timeout(lv_event_t * e);
void change_volume(lv_event_t * e);
void set_system_unit(lv_event_t * e);
void set_background(lv_event_t * e);
void device_factory_reset(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
