// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: SettingsScreen_HMI

#include "ui.h"

lv_obj_t * ui_FWUpdateScreen = NULL;
lv_obj_t * ui_fwupdtcontinaer = NULL;
lv_obj_t * ui_backgesture5 = NULL;
lv_obj_t * ui_FWUpdatespinner = NULL;
lv_obj_t * ui_Fwupdatespinrlabel = NULL;
lv_obj_t * ui_Fwupdatelatestlbl = NULL;
lv_obj_t * ui_Fwupdateavaillabel = NULL;
lv_obj_t * ui_fwdownloadbtn = NULL;
lv_obj_t * ui_fwdownloadbtnlbl = NULL;
lv_obj_t * ui_fwpanel = NULL;
lv_obj_t * ui_updateimg = NULL;
lv_obj_t * ui_homeimg = NULL;
// event funtions
void ui_event_homeimg(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ActiveScreen, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_ActiveScreen_screen_init);
    }
}

// build funtions

void ui_FWUpdateScreen_screen_init(void)
{
    ui_FWUpdateScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_FWUpdateScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_FWUpdateScreen, lv_color_hex(0x06534B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FWUpdateScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fwupdtcontinaer = lv_obj_create(ui_FWUpdateScreen);
    lv_obj_remove_style_all(ui_fwupdtcontinaer);
    lv_obj_set_width(ui_fwupdtcontinaer, 475);
    lv_obj_set_height(ui_fwupdtcontinaer, 479);
    lv_obj_set_x(ui_fwupdtcontinaer, -12);
    lv_obj_set_y(ui_fwupdtcontinaer, -1);
    lv_obj_set_align(ui_fwupdtcontinaer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_fwupdtcontinaer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_backgesture5 = lv_button_create(ui_fwupdtcontinaer);
    lv_obj_set_width(ui_backgesture5, 460);
    lv_obj_set_height(ui_backgesture5, 467);
    lv_obj_set_x(ui_backgesture5, -1);
    lv_obj_set_y(ui_backgesture5, 4);
    lv_obj_set_align(ui_backgesture5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backgesture5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_backgesture5, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_backgesture5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backgesture5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_backgesture5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_backgesture5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FWUpdatespinner = lv_spinner_create(ui_backgesture5);
    //lv_spinner_set_anim_params(ui_FWUpdatespinner, 1000, 90);
    lv_obj_set_width(ui_FWUpdatespinner, 80);
    lv_obj_set_height(ui_FWUpdatespinner, 80);
    lv_obj_set_x(ui_FWUpdatespinner, -9);
    lv_obj_set_y(ui_FWUpdatespinner, -39);
    lv_obj_set_align(ui_FWUpdatespinner, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_FWUpdatespinner, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_color(ui_FWUpdatespinner, lv_color_hex(0xFCFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_FWUpdatespinner, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_FWUpdatespinner, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_FWUpdatespinner, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_FWUpdatespinner, lv_color_hex(0x12A24A), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_FWUpdatespinner, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_FWUpdatespinner, 11, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Fwupdatespinrlabel = lv_label_create(ui_backgesture5);
    lv_obj_set_width(ui_Fwupdatespinrlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Fwupdatespinrlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Fwupdatespinrlabel, 5);
    lv_obj_set_y(ui_Fwupdatespinrlabel, 44);
    lv_obj_set_align(ui_Fwupdatespinrlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Fwupdatespinrlabel, "Checking for updates . . .");
    lv_obj_set_style_text_font(ui_Fwupdatespinrlabel, &ui_font_sans30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Fwupdatelatestlbl = lv_label_create(ui_backgesture5);
    lv_obj_set_width(ui_Fwupdatelatestlbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Fwupdatelatestlbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Fwupdatelatestlbl, -14);
    lv_obj_set_y(ui_Fwupdatelatestlbl, -108);
    lv_obj_set_align(ui_Fwupdatelatestlbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Fwupdatelatestlbl, "Firmware is up to date.");
    lv_obj_add_flag(ui_Fwupdatelatestlbl, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_Fwupdatelatestlbl, &ui_font_sans30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Fwupdateavaillabel = lv_label_create(ui_backgesture5);
    lv_obj_set_width(ui_Fwupdateavaillabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Fwupdateavaillabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Fwupdateavaillabel, -4);
    lv_obj_set_y(ui_Fwupdateavaillabel, -108);
    lv_obj_set_align(ui_Fwupdateavaillabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Fwupdateavaillabel, "New firmware version found");
    lv_obj_add_flag(ui_Fwupdateavaillabel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_Fwupdateavaillabel, &ui_font_sans30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fwdownloadbtn = lv_button_create(ui_backgesture5);
    lv_obj_set_width(ui_fwdownloadbtn, 199);
    lv_obj_set_height(ui_fwdownloadbtn, 50);
    lv_obj_set_x(ui_fwdownloadbtn, -1);
    lv_obj_set_y(ui_fwdownloadbtn, -40);
    lv_obj_set_align(ui_fwdownloadbtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_fwdownloadbtn, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_fwdownloadbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_fwdownloadbtn, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_fwdownloadbtn, lv_color_hex(0x525050), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fwdownloadbtn, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_fwdownloadbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_fwdownloadbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_fwdownloadbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fwdownloadbtnlbl = lv_label_create(ui_fwdownloadbtn);
    lv_obj_set_width(ui_fwdownloadbtnlbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fwdownloadbtnlbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_fwdownloadbtnlbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_fwdownloadbtnlbl, "Download");
    lv_obj_set_style_text_font(ui_fwdownloadbtnlbl, &ui_font_sans24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fwpanel = lv_obj_create(ui_backgesture5);
    lv_obj_set_width(ui_fwpanel, 78);
    lv_obj_set_height(ui_fwpanel, 75);
    lv_obj_set_x(ui_fwpanel, -9);
    lv_obj_set_y(ui_fwpanel, -194);
    lv_obj_set_align(ui_fwpanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_fwpanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_fwpanel, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_fwpanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fwpanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_fwpanel, lv_color_hex(0x30AD29), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_fwpanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_fwpanel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_fwpanel, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_fwpanel, lv_color_hex(0x06AD63), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_fwpanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_fwpanel, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_fwpanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_updateimg = lv_image_create(ui_fwpanel);
    lv_image_set_src(ui_updateimg, &ui_img_149480563);
    lv_obj_set_width(ui_updateimg, LV_SIZE_CONTENT);   /// 70
    lv_obj_set_height(ui_updateimg, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_updateimg, 1);
    lv_obj_set_y(ui_updateimg, -2);
    lv_obj_set_align(ui_updateimg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_updateimg, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_updateimg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_homeimg = lv_image_create(ui_FWUpdateScreen);
    lv_image_set_src(ui_homeimg, &ui_img_icn_home_png);
    lv_obj_set_width(ui_homeimg, 70);
    lv_obj_set_height(ui_homeimg, 70);
    lv_obj_set_x(ui_homeimg, -23);
    lv_obj_set_y(ui_homeimg, 187);
    lv_obj_set_align(ui_homeimg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_homeimg, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_homeimg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_homeimg, ui_event_homeimg, LV_EVENT_ALL, NULL);

}

void ui_FWUpdateScreen_screen_destroy(void)
{
    if(ui_FWUpdateScreen) lv_obj_del(ui_FWUpdateScreen);

    // NULL screen variables
    ui_FWUpdateScreen = NULL;
    ui_fwupdtcontinaer = NULL;
    ui_backgesture5 = NULL;
    ui_FWUpdatespinner = NULL;
    ui_Fwupdatespinrlabel = NULL;
    ui_Fwupdatelatestlbl = NULL;
    ui_Fwupdateavaillabel = NULL;
    ui_fwdownloadbtn = NULL;
    ui_fwdownloadbtnlbl = NULL;
    ui_fwpanel = NULL;
    ui_updateimg = NULL;
    ui_homeimg = NULL;
}
