// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: Thermostat_HMI

#include "ui.h"

lv_obj_t * ui_FWUpdateScreen;
lv_obj_t * ui_fwupdtcontinaer;
lv_obj_t * ui_fwupdtscreenlbl;
lv_obj_t * ui_backgesture5;
lv_obj_t * ui_homebtnimg6;
lv_obj_t * ui_homebtn6;
lv_obj_t * ui_FWUpdatespinner;
lv_obj_t * ui_Fwupdatespinrlabel;
lv_obj_t * ui_Fwupdatelatestlbl;
lv_obj_t * ui_Fwupdateavaillabel;
lv_obj_t * ui_fwdownloadbtn;
lv_obj_t * ui_fwdownloadbtnlbl;

// event funtions
void ui_event_backgesture5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());

        _ui_screen_change(&ui_SystemSettings, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 230, 0, &ui_SystemSettings_screen_init);
    }
}

void ui_event_homebtn6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ActiveScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 230, 0, &ui_ActiveScreen_screen_init);
    }
}




// build funtions

void ui_FWUpdateScreen_screen_init(void)
{
    ui_FWUpdateScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_FWUpdateScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_FWUpdateScreen, lv_color_hex(0x08665C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FWUpdateScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fwupdtcontinaer = lv_obj_create(ui_FWUpdateScreen);
    lv_obj_remove_style_all(ui_fwupdtcontinaer);
    lv_obj_set_width(ui_fwupdtcontinaer, 475);
    lv_obj_set_height(ui_fwupdtcontinaer, 479);
    lv_obj_set_x(ui_fwupdtcontinaer, -12);
    lv_obj_set_y(ui_fwupdtcontinaer, -1);
    lv_obj_set_align(ui_fwupdtcontinaer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_fwupdtcontinaer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_fwupdtscreenlbl = lv_label_create(ui_fwupdtcontinaer);
    lv_obj_set_width(ui_fwupdtscreenlbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fwupdtscreenlbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_fwupdtscreenlbl, -19);
    lv_obj_set_y(ui_fwupdtscreenlbl, -198);
    lv_obj_set_align(ui_fwupdtscreenlbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_fwupdtscreenlbl, "Firmware Update");
    lv_obj_set_style_text_color(ui_fwupdtscreenlbl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_fwupdtscreenlbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_fwupdtscreenlbl, &ui_font_sans36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backgesture5 = lv_button_create(ui_fwupdtcontinaer);
    lv_obj_set_width(ui_backgesture5, 460);
    lv_obj_set_height(ui_backgesture5, 467);
    lv_obj_set_x(ui_backgesture5, -1);
    lv_obj_set_y(ui_backgesture5, 4);
    lv_obj_set_align(ui_backgesture5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backgesture5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_backgesture5, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_backgesture5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backgesture5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_backgesture5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_backgesture5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_homebtnimg6 = lv_image_create(ui_backgesture5);
    lv_image_set_src(ui_homebtnimg6, &ui_img_344061264);
    lv_obj_set_width(ui_homebtnimg6, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_homebtnimg6, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_homebtnimg6, 179);
    lv_obj_set_y(ui_homebtnimg6, -194);
    lv_obj_set_align(ui_homebtnimg6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_homebtnimg6, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_homebtnimg6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_homebtn6 = lv_button_create(ui_backgesture5);
    lv_obj_set_width(ui_homebtn6, 61);
    lv_obj_set_height(ui_homebtn6, 68);
    lv_obj_set_x(ui_homebtn6, 179);
    lv_obj_set_y(ui_homebtn6, -194);
    lv_obj_set_align(ui_homebtn6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_homebtn6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_homebtn6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_homebtn6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_homebtn6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FWUpdatespinner = lv_spinner_create(ui_backgesture5);
    //lv_spinner_set_anim_params(ui_FWUpdatespinner, 1000, 90);
    lv_obj_set_width(ui_FWUpdatespinner, 80);
    lv_obj_set_height(ui_FWUpdatespinner, 80);
    lv_obj_set_x(ui_FWUpdatespinner, -9);
    lv_obj_set_y(ui_FWUpdatespinner, -39);
    lv_obj_set_align(ui_FWUpdatespinner, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_FWUpdatespinner, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_color(ui_FWUpdatespinner, lv_color_hex(0xFCFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_FWUpdatespinner, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_FWUpdatespinner, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_FWUpdatespinner, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_FWUpdatespinner, lv_color_hex(0x848488), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_FWUpdatespinner, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Fwupdatespinrlabel = lv_label_create(ui_backgesture5);
    lv_obj_set_width(ui_Fwupdatespinrlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Fwupdatespinrlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Fwupdatespinrlabel, -14);
    lv_obj_set_y(ui_Fwupdatespinrlabel, 38);
    lv_obj_set_align(ui_Fwupdatespinrlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Fwupdatespinrlabel, "Checking for updates . . .");
    lv_obj_set_style_text_font(ui_Fwupdatespinrlabel, &ui_font_sans30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Fwupdatelatestlbl = lv_label_create(ui_backgesture5);
    lv_obj_set_width(ui_Fwupdatelatestlbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Fwupdatelatestlbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Fwupdatelatestlbl, -14);
    lv_obj_set_y(ui_Fwupdatelatestlbl, -108);
    lv_obj_set_align(ui_Fwupdatelatestlbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Fwupdatelatestlbl, "Firmware is up to date.");
    lv_obj_add_flag(ui_Fwupdatelatestlbl, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_Fwupdatelatestlbl, &ui_font_sans30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Fwupdateavaillabel = lv_label_create(ui_backgesture5);
    lv_obj_set_width(ui_Fwupdateavaillabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Fwupdateavaillabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Fwupdateavaillabel, -4);
    lv_obj_set_y(ui_Fwupdateavaillabel, -108);
    lv_obj_set_align(ui_Fwupdateavaillabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Fwupdateavaillabel, "New firmware version found");
    lv_obj_add_flag(ui_Fwupdateavaillabel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_Fwupdateavaillabel, &ui_font_sans30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fwdownloadbtn = lv_button_create(ui_backgesture5);
    lv_obj_set_width(ui_fwdownloadbtn, 199);
    lv_obj_set_height(ui_fwdownloadbtn, 50);
    lv_obj_set_x(ui_fwdownloadbtn, -1);
    lv_obj_set_y(ui_fwdownloadbtn, -40);
    lv_obj_set_align(ui_fwdownloadbtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_fwdownloadbtn, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_fwdownloadbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_fwdownloadbtn, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_fwdownloadbtn, lv_color_hex(0x525050), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fwdownloadbtn, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_fwdownloadbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_fwdownloadbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_fwdownloadbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fwdownloadbtnlbl = lv_label_create(ui_fwdownloadbtn);
    lv_obj_set_width(ui_fwdownloadbtnlbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fwdownloadbtnlbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_fwdownloadbtnlbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_fwdownloadbtnlbl, "Download");
    lv_obj_set_style_text_font(ui_fwdownloadbtnlbl, &ui_font_sans24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_homebtn6, ui_event_homebtn6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_backgesture5, ui_event_backgesture5, LV_EVENT_ALL, NULL);

}

void ui_FWUpdateScreen_screen_destroy(void)
{
    if(ui_FWUpdateScreen) lv_obj_del(ui_FWUpdateScreen);

    // NULL screen variables
    ui_FWUpdateScreen = NULL;
    ui_fwupdtcontinaer = NULL;
    ui_fwupdtscreenlbl = NULL;
    ui_backgesture5 = NULL;
    ui_homebtnimg6 = NULL;
    ui_homebtn6 = NULL;
    ui_FWUpdatespinner = NULL;
    ui_Fwupdatespinrlabel = NULL;
    ui_Fwupdatelatestlbl = NULL;
    ui_Fwupdateavaillabel = NULL;
    ui_fwdownloadbtn = NULL;
    ui_fwdownloadbtnlbl = NULL;

}
