// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: SettingsScreen_HMI

#include "ui.h"

lv_obj_t * ui_FWUpdateScreen;
lv_obj_t * ui_fwupdtcontinaer;
lv_obj_t * ui_fwupdtscreenlbl;
lv_obj_t * ui_backgesture5;
lv_obj_t * ui_homebtnimg6;
lv_obj_t * ui_homebtn6;
lv_obj_t * ui_Fwupdateavaillabel;
lv_obj_t * ui_Bar2;

// event funtions
void ui_event_backgesture5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_SystemSettings, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 30, 0, &ui_SystemSettings_screen_init);
    }
}

void ui_event_homebtn6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ActiveScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 30, 0, &ui_ActiveScreen_screen_init);
    }
}

// build funtions


void ui_FWUpdateScreen_screen_init(void)
{
    ui_FWUpdateScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_FWUpdateScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_FWUpdateScreen, lv_color_hex(0x06534B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FWUpdateScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fwupdtcontinaer = lv_obj_create(ui_FWUpdateScreen);
    lv_obj_remove_style_all(ui_fwupdtcontinaer);
    lv_obj_set_width(ui_fwupdtcontinaer, 475);
    lv_obj_set_height(ui_fwupdtcontinaer, 479);
    lv_obj_set_x(ui_fwupdtcontinaer, -12);
    lv_obj_set_y(ui_fwupdtcontinaer, -1);
    lv_obj_set_align(ui_fwupdtcontinaer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_fwupdtcontinaer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_fwupdtscreenlbl = lv_label_create(ui_fwupdtcontinaer);
    lv_obj_set_width(ui_fwupdtscreenlbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fwupdtscreenlbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_fwupdtscreenlbl, -19);
    lv_obj_set_y(ui_fwupdtscreenlbl, -198);
    lv_obj_set_align(ui_fwupdtscreenlbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_fwupdtscreenlbl, "Firmware Update");
    lv_obj_set_style_text_color(ui_fwupdtscreenlbl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_fwupdtscreenlbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_fwupdtscreenlbl, &ui_font_sans36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backgesture5 = lv_button_create(ui_fwupdtcontinaer);
    lv_obj_set_width(ui_backgesture5, 460);
    lv_obj_set_height(ui_backgesture5, 467);
    lv_obj_set_x(ui_backgesture5, -1);
    lv_obj_set_y(ui_backgesture5, 4);
    lv_obj_set_align(ui_backgesture5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backgesture5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_backgesture5, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_backgesture5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backgesture5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_backgesture5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_backgesture5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_homebtnimg6 = lv_image_create(ui_backgesture5);
    lv_image_set_src(ui_homebtnimg6, &ui_img_344061264);
    lv_obj_set_width(ui_homebtnimg6, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_homebtnimg6, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_homebtnimg6, 179);
    lv_obj_set_y(ui_homebtnimg6, -194);
    lv_obj_set_align(ui_homebtnimg6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_homebtnimg6, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_homebtnimg6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_homebtn6 = lv_button_create(ui_backgesture5);
    lv_obj_set_width(ui_homebtn6, 61);
    lv_obj_set_height(ui_homebtn6, 68);
    lv_obj_set_x(ui_homebtn6, 179);
    lv_obj_set_y(ui_homebtn6, -194);
    lv_obj_set_align(ui_homebtn6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_homebtn6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_homebtn6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_homebtn6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_homebtn6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Fwupdateavaillabel = lv_label_create(ui_backgesture5);
    lv_obj_set_width(ui_Fwupdateavaillabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Fwupdateavaillabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Fwupdateavaillabel, -4);
    lv_obj_set_y(ui_Fwupdateavaillabel, -5);
    lv_obj_set_align(ui_Fwupdateavaillabel, LV_ALIGN_CENTER);

    lv_label_set_text(ui_Fwupdateavaillabel, "Firmware update is in progress.\nPlease wait for 10 minutes.....");
    lv_obj_set_style_text_font(ui_Fwupdateavaillabel, &ui_font_sans28, LV_PART_MAIN | LV_STATE_DEFAULT);


    lv_obj_add_event_cb(ui_homebtn6, ui_event_homebtn6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_backgesture5, ui_event_backgesture5, LV_EVENT_ALL, NULL);

}

void ui_FWUpdateScreen_update_msg(char *msg)
{
    lv_label_set_text(ui_Fwupdateavaillabel, msg);
    lv_obj_set_style_text_font(ui_Fwupdateavaillabel, &ui_font_sans28, LV_PART_MAIN | LV_STATE_DEFAULT);
}

void ui_FWUpdateScreen_screen_destroy(void)
{
    if(ui_FWUpdateScreen) lv_obj_del(ui_FWUpdateScreen);

    // NULL screen variables
    ui_FWUpdateScreen = NULL;
    ui_fwupdtcontinaer = NULL;
    ui_fwupdtscreenlbl = NULL;
    ui_backgesture5 = NULL;
    ui_homebtnimg6 = NULL;
    ui_homebtn6 = NULL;
    ui_Fwupdateavaillabel = NULL;
    ui_Bar2 = NULL;

}
