// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Thermostat_HMI

#include "ui.h"

void ui_LPScreen_screen_init(void)
{
    ui_LPScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_LPScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LPScreen, lv_color_hex(0x1A1B1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LPScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LPScreen, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_LPScreen);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 473);
    lv_obj_set_height(ui_Container2, 479);
    lv_obj_set_x(ui_Container2, -18);
    lv_obj_set_y(ui_Container2, -2);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    // lv_obj_set_style_border_color(ui_Container2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_border_opa(ui_Container2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_border_width(ui_Container2, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainTemptextLP = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_MainTemptextLP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MainTemptextLP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MainTemptextLP, 6);
    lv_obj_set_y(ui_MainTemptextLP, -19);
    lv_obj_set_align(ui_MainTemptextLP, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MainTemptextLP, "24°c");
    lv_obj_set_style_text_color(ui_MainTemptextLP, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MainTemptextLP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MainTemptextLP, &ui_font_Roboto80, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeColonLP = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_TimeColonLP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeColonLP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeColonLP, -20);
    lv_obj_set_y(ui_TimeColonLP, -160);
    lv_obj_set_align(ui_TimeColonLP, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimeColonLP, ":");
    lv_obj_set_style_text_color(ui_TimeColonLP, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TimeColonLP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TimeColonLP, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeColonLP2 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_TimeColonLP2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeColonLP2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeColonLP2, 34);
    lv_obj_set_y(ui_TimeColonLP2, -160);
    lv_obj_set_align(ui_TimeColonLP2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimeColonLP2, ":");
    lv_obj_set_style_text_color(ui_TimeColonLP2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TimeColonLP2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TimeColonLP2, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeHLP = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_TimeHLP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeHLP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeHLP, -48);
    lv_obj_set_y(ui_TimeHLP, -155);
    lv_obj_set_align(ui_TimeHLP, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimeHLP, "");
    lv_obj_set_style_text_color(ui_TimeHLP, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TimeHLP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TimeHLP, &ui_font_sans34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeMLP = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_TimeMLP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeMLP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeMLP, 6);
    lv_obj_set_y(ui_TimeMLP, -155);
    lv_obj_set_align(ui_TimeMLP, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimeMLP, "");
    lv_obj_set_style_text_color(ui_TimeMLP, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TimeMLP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TimeMLP, &ui_font_sans34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeSLP = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_TimeSLP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeSLP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeSLP, 60);
    lv_obj_set_y(ui_TimeSLP, -155);
    lv_obj_set_align(ui_TimeSLP, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimeSLP, "");
    lv_obj_set_style_text_color(ui_TimeSLP, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TimeSLP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TimeSLP, &ui_font_sans34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ecoLP = lv_image_create(ui_Container2);
    lv_image_set_src(ui_ecoLP, &ui_img_eco_png);
    lv_obj_set_width(ui_ecoLP, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_ecoLP, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_ecoLP, 6);
    lv_obj_set_y(ui_ecoLP, 157);
    lv_obj_set_align(ui_ecoLP, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ecoLP, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_ecoLP, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DateLP = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_DateLP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DateLP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DateLP, 8);
    lv_obj_set_y(ui_DateLP, -197);
    lv_obj_set_align(ui_DateLP, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DateLP, "");
    lv_obj_set_style_text_color(ui_DateLP, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DateLP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DateLP, &ui_font_sans30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_changescreenLP = lv_button_create(ui_LPScreen);
    lv_obj_set_width(ui_changescreenLP, 453);
    lv_obj_set_height(ui_changescreenLP, 451);
    lv_obj_set_x(ui_changescreenLP, -15);
    lv_obj_set_y(ui_changescreenLP, 1);
    lv_obj_set_align(ui_changescreenLP, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_changescreenLP, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_changescreenLP, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_changescreenLP, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_changescreenLP, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_changescreenLP, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_changescreenLP, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_changescreenLP, ui_event_changescreenLP, LV_EVENT_ALL, NULL);

}
