// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: SettingsScreen_HMI

#include "ui.h"

lv_obj_t * ui_SystemSettings;
lv_obj_t * ui_Container5;
lv_obj_t * ui_backgesture1;
lv_obj_t * ui_Label13;
lv_obj_t * ui_Panel9;
lv_obj_t * ui_Label15;
lv_obj_t * ui_Panel10;
lv_obj_t * ui_Panel11;
lv_obj_t * ui_Panel12;
lv_obj_t * ui_Label16;
lv_obj_t * ui_Label17;
lv_obj_t * ui_homebtnimg1;
lv_obj_t * ui_homebtn1;
lv_obj_t * ui_tempunitlbl;
lv_obj_t * ui_tempunitswitch;
lv_obj_t * ui_timeoutdropdown;
lv_obj_t * ui_factoryresetcontianer;
lv_obj_t * ui_AbtLabel23;
lv_obj_t * ui_AbtLabel24;
lv_obj_t * ui_confirmbtn;
lv_obj_t * ui_confirmbtnlbl;
lv_obj_t * ui_cancelbtn;
lv_obj_t * ui_cancelbtnlbl;
lv_obj_t * ui_AbtLabel2;
lv_obj_t * ui_systemscreenlbl;

// event funtions
void ui_event_backgesture1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_SettingsScreen, LV_SCR_LOAD_ANIM_FADE_IN, 30, 0, &ui_SettingsScreen_screen_init);
    }
}

void ui_event_Label15(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_factoryresetcontianer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_Label16(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_DateTimeSettings, LV_SCR_LOAD_ANIM_FADE_ON, 30, 0, &ui_DateTimeSettings_screen_init);
    }
}

void ui_event_Label17(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_AboutScreen, LV_SCR_LOAD_ANIM_FADE_ON, 30, 0, &ui_AboutScreen_screen_init);

        _ui_flag_modify(ui_checkupdtbtn, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        lv_label_set_text(ui_getfwverdetails, "-.-.-");
        _ui_flag_modify(ui_downloadfwbtn, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);

    }
}

void ui_event_homebtn1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ActiveScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 30, 0, &ui_ActiveScreen_screen_init);
    }
}

void ui_event_tempunitswitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        set_system_unit(e);
    }
}

void ui_event_timeoutdropdown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        change_idle_timeout(e);
    }
}

void ui_event_confirmbtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        device_factory_reset(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_factoryresetcontianer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_cancelbtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_factoryresetcontianer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_Label2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_DateTimeSettings, LV_SCR_LOAD_ANIM_FADE_ON, 30, 0, &ui_DateTimeSettings_screen_init);
    }
}

// build funtions

void ui_SystemSettings_screen_init(void)
{
    ui_SystemSettings = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_SystemSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SystemSettings, lv_color_hex(0x06534B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SystemSettings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container5 = lv_obj_create(ui_SystemSettings);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, 475);
    lv_obj_set_height(ui_Container5, 479);
    lv_obj_set_x(ui_Container5, -17);
    lv_obj_set_y(ui_Container5, -2);
    lv_obj_set_align(ui_Container5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_backgesture1 = lv_button_create(ui_Container5);
    lv_obj_set_width(ui_backgesture1, 460);
    lv_obj_set_height(ui_backgesture1, 467);
    lv_obj_set_x(ui_backgesture1, 0);
    lv_obj_set_y(ui_backgesture1, 2);
    lv_obj_set_align(ui_backgesture1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backgesture1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_backgesture1, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_backgesture1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backgesture1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_backgesture1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_backgesture1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_backgesture1);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, -137);
    lv_obj_set_y(ui_Label13, -135);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Idle Timeout");
    lv_obj_add_flag(ui_Label13, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &ui_font_sans32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel9 = lv_obj_create(ui_backgesture1);
    lv_obj_set_width(ui_Panel9, 460);
    lv_obj_set_height(ui_Panel9, 3);
    lv_obj_set_x(ui_Panel9, 0);
    lv_obj_set_y(ui_Panel9, -99);
    lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Panel9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Panel9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_backgesture1);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, -128);
    lv_obj_set_y(ui_Label15, 27);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "Factory Reset");
    lv_obj_add_flag(ui_Label15, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label15, &ui_font_sans32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AbtLabel2 = lv_label_create(ui_backgesture1);
    lv_obj_set_width(ui_AbtLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AbtLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AbtLabel2, -123);
    lv_obj_set_y(ui_AbtLabel2, 112);
    lv_obj_set_align(ui_AbtLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AbtLabel2, "Date and Time");
    lv_obj_add_flag(ui_AbtLabel2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_AbtLabel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AbtLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AbtLabel2, &ui_font_sans32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel10 = lv_obj_create(ui_backgesture1);
    lv_obj_set_width(ui_Panel10, 460);
    lv_obj_set_height(ui_Panel10, 3);
    lv_obj_set_x(ui_Panel10, -2);
    lv_obj_set_y(ui_Panel10, 70);
    lv_obj_set_align(ui_Panel10, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Panel10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Panel10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel11 = lv_obj_create(ui_backgesture1);
    lv_obj_set_width(ui_Panel11, 460);
    lv_obj_set_height(ui_Panel11, 3);
    lv_obj_set_x(ui_Panel11, -3);
    lv_obj_set_y(ui_Panel11, 155);
    lv_obj_set_align(ui_Panel11, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel11, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Panel11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Panel11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel12 = lv_obj_create(ui_backgesture1);
    lv_obj_set_width(ui_Panel12, 460);
    lv_obj_set_height(ui_Panel12, 3);
    lv_obj_set_x(ui_Panel12, -2);
    lv_obj_set_y(ui_Panel12, -17);
    lv_obj_set_align(ui_Panel12, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel12, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Panel12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Panel12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

//    ui_Label16 = lv_label_create(ui_backgesture1);
//    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
//    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
//    lv_obj_set_x(ui_Label16, -103);
//    lv_obj_set_y(ui_Label16, 112);
//    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
//    lv_label_set_text(ui_Label16, "Firmware Update");
//    lv_obj_add_flag(ui_Label16, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
//    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
//    lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
//    lv_obj_set_style_text_font(ui_Label16, &ui_font_sans32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_backgesture1);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
//    lv_obj_set_x(ui_Label17, -180);
    lv_obj_set_x(ui_Label17, -103);
    lv_obj_set_y(ui_Label17, 193);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "Firmware Update");
    lv_obj_add_flag(ui_Label17, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Label17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label17, &ui_font_sans32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_homebtnimg1 = lv_image_create(ui_backgesture1);
    lv_image_set_src(ui_homebtnimg1, &ui_img_344061264);
    lv_obj_set_width(ui_homebtnimg1, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_homebtnimg1, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_homebtnimg1, 179);
    lv_obj_set_y(ui_homebtnimg1, -194);
    lv_obj_set_align(ui_homebtnimg1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_homebtnimg1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_homebtnimg1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_homebtn1 = lv_button_create(ui_backgesture1);
    lv_obj_set_width(ui_homebtn1, 61);
    lv_obj_set_height(ui_homebtn1, 68);
    lv_obj_set_x(ui_homebtn1, 179);
    lv_obj_set_y(ui_homebtn1, -194);
    lv_obj_set_align(ui_homebtn1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_homebtn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_homebtn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_homebtn1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_homebtn1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempunitlbl = lv_label_create(ui_backgesture1);
    lv_obj_set_width(ui_tempunitlbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempunitlbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempunitlbl, -77);
    lv_obj_set_y(ui_tempunitlbl, -59);
    lv_obj_set_align(ui_tempunitlbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempunitlbl, "Temperature Unit (°F)");
    lv_obj_set_style_text_color(ui_tempunitlbl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tempunitlbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tempunitlbl, &ui_font_sans32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempunitswitch = lv_switch_create(ui_backgesture1);
    lv_obj_set_width(ui_tempunitswitch, 50);
    lv_obj_set_height(ui_tempunitswitch, 25);
    lv_obj_set_x(ui_tempunitswitch, 111);
    lv_obj_set_y(ui_tempunitswitch, -62);
    lv_obj_set_align(ui_tempunitswitch, LV_ALIGN_CENTER);

    ui_timeoutdropdown = lv_dropdown_create(ui_backgesture1);
    lv_dropdown_set_options(ui_timeoutdropdown, "3 second\n5 second\n10 second\n20 second\n30 second\nNever");
    lv_obj_set_width(ui_timeoutdropdown, 150);
    lv_obj_set_height(ui_timeoutdropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timeoutdropdown, 54);
    lv_obj_set_y(ui_timeoutdropdown, -138);
    lv_obj_set_align(ui_timeoutdropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_timeoutdropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_factoryresetcontianer = lv_obj_create(ui_backgesture1);
    lv_obj_remove_style_all(ui_factoryresetcontianer);
    lv_obj_set_width(ui_factoryresetcontianer, 441);
    lv_obj_set_height(ui_factoryresetcontianer, 301);
    lv_obj_set_x(ui_factoryresetcontianer, -2);
    lv_obj_set_y(ui_factoryresetcontianer, -5);
    lv_obj_set_align(ui_factoryresetcontianer, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_factoryresetcontianer, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_factoryresetcontianer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_factoryresetcontianer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_factoryresetcontianer, lv_color_hex(0x212020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_factoryresetcontianer, 240, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AbtLabel23 = lv_label_create(ui_factoryresetcontianer);
    lv_obj_set_width(ui_AbtLabel23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AbtLabel23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AbtLabel23, -6);
    lv_obj_set_y(ui_AbtLabel23, -116);
    lv_obj_set_align(ui_AbtLabel23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AbtLabel23, "Factory Reset");
    lv_obj_set_style_text_color(ui_AbtLabel23, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AbtLabel23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_AbtLabel23, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_AbtLabel23, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_AbtLabel23, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AbtLabel23, &ui_font_sans22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AbtLabel24 = lv_label_create(ui_factoryresetcontianer);
    lv_obj_set_width(ui_AbtLabel24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AbtLabel24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AbtLabel24, 5);
    lv_obj_set_y(ui_AbtLabel24, -37);
    lv_obj_set_align(ui_AbtLabel24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AbtLabel24, "Restore default configuration and \ndelete saved credentials ?");
    lv_obj_set_style_text_color(ui_AbtLabel24, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AbtLabel24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_AbtLabel24, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_AbtLabel24, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_AbtLabel24, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AbtLabel24, &ui_font_sans22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_confirmbtn = lv_button_create(ui_factoryresetcontianer);
    lv_obj_set_width(ui_confirmbtn, 116);
    lv_obj_set_height(ui_confirmbtn, 50);
    lv_obj_set_x(ui_confirmbtn, 87);
    lv_obj_set_y(ui_confirmbtn, 31);
    lv_obj_set_align(ui_confirmbtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_confirmbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_confirmbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_confirmbtn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_confirmbtn, lv_color_hex(0xF34C4C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_confirmbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_confirmbtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_confirmbtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_confirmbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_confirmbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_confirmbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_confirmbtnlbl = lv_label_create(ui_confirmbtn);
    lv_obj_set_width(ui_confirmbtnlbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_confirmbtnlbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_confirmbtnlbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_confirmbtnlbl, "Confirm");
    lv_obj_set_style_text_color(ui_confirmbtnlbl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_confirmbtnlbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_confirmbtnlbl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_confirmbtnlbl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_confirmbtnlbl, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_confirmbtnlbl, &ui_font_sans22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cancelbtn = lv_button_create(ui_factoryresetcontianer);
    lv_obj_set_width(ui_cancelbtn, 116);
    lv_obj_set_height(ui_cancelbtn, 50);
    lv_obj_set_x(ui_cancelbtn, -106);
    lv_obj_set_y(ui_cancelbtn, 31);
    lv_obj_set_align(ui_cancelbtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_cancelbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_cancelbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_cancelbtn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cancelbtn, lv_color_hex(0xF34C4C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cancelbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cancelbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_cancelbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_cancelbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cancelbtnlbl = lv_label_create(ui_cancelbtn);
    lv_obj_set_width(ui_cancelbtnlbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cancelbtnlbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_cancelbtnlbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cancelbtnlbl, "Cancel");
    lv_obj_set_style_text_color(ui_cancelbtnlbl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cancelbtnlbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_cancelbtnlbl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_cancelbtnlbl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_cancelbtnlbl, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cancelbtnlbl, &ui_font_sans22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_systemscreenlbl = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_systemscreenlbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_systemscreenlbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_systemscreenlbl, -19);
    lv_obj_set_y(ui_systemscreenlbl, -198);
    lv_obj_set_align(ui_systemscreenlbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_systemscreenlbl, "System Settings");
    lv_obj_set_style_text_color(ui_systemscreenlbl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_systemscreenlbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_systemscreenlbl, &ui_font_sans36, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Label15, ui_event_Label15, LV_EVENT_ALL, NULL);
//    lv_obj_add_event_cb(ui_Label16, ui_event_Label16, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Label17, ui_event_Label17, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_homebtn1, ui_event_homebtn1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_tempunitswitch, ui_event_tempunitswitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_timeoutdropdown, ui_event_timeoutdropdown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_confirmbtn, ui_event_confirmbtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cancelbtn, ui_event_cancelbtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AbtLabel2, ui_event_Label2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_backgesture1, ui_event_backgesture1, LV_EVENT_ALL, NULL);

}

void ui_SystemSettings_screen_destroy(void)
{
    if(ui_SystemSettings) lv_obj_del(ui_SystemSettings);

    // NULL screen variables
    ui_SystemSettings = NULL;
    ui_Container5 = NULL;
    ui_backgesture1 = NULL;
    ui_Label13 = NULL;
    ui_Panel9 = NULL;
    ui_Label15 = NULL;
    ui_Panel10 = NULL;
    ui_Panel11 = NULL;
    ui_Panel12 = NULL;
    ui_Label16 = NULL;
    ui_Label17 = NULL;
    ui_homebtnimg1 = NULL;
    ui_homebtn1 = NULL;
    ui_tempunitlbl = NULL;
    ui_tempunitswitch = NULL;
    ui_timeoutdropdown = NULL;
    ui_factoryresetcontianer = NULL;
    ui_AbtLabel23 = NULL;
    ui_AbtLabel24 = NULL;
    ui_confirmbtn = NULL;
    ui_confirmbtnlbl = NULL;
    ui_cancelbtn = NULL;
    ui_cancelbtnlbl = NULL;
    ui_AbtLabel2 = NULL;
    ui_systemscreenlbl = NULL;

}
