// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: SettingsScreen_HMI

#include "ui.h"

lv_obj_t * ui_SettingsScreen = NULL;
lv_obj_t * ui_Container3 = NULL;
lv_obj_t * ui_Slider2 = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_upimg = NULL;
lv_obj_t * ui_timeoutdropdown = NULL;
lv_obj_t * ui_Dropdown2 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_Image6 = NULL;
lv_obj_t * ui_tempunitswitch = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Image8 = NULL;
lv_obj_t * ui_Image9 = NULL;
lv_obj_t * ui_reset = NULL;
lv_obj_t * ui_factoryresetcontianer = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_confirmbtn2 = NULL;
lv_obj_t * ui_confirmbtnlbl2 = NULL;
lv_obj_t * ui_cancelbtn2 = NULL;
lv_obj_t * ui_cancelbtnlbl2 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Label8 = NULL;
// event funtions
void ui_event_Slider2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        change_brightness(e);
    }
}

void ui_event_upimg(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ActiveScreen, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_ActiveScreen_screen_init);
    }
}

void ui_event_timeoutdropdown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        change_idle_timeout(e);
    }
}

void ui_event_Dropdown2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        change_volume(e);
    }
}

void ui_event_tempunitswitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        set_system_unit(e);
    }
}

void ui_event_Image8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_FWUpdateScreen, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_FWUpdateScreen_screen_init);
    }
}

void ui_event_reset(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_factoryresetcontianer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_confirmbtn2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        device_factory_reset(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_factoryresetcontianer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_cancelbtn2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_factoryresetcontianer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

// build funtions

void ui_SettingsScreen_screen_init(void)
{
    ui_SettingsScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_SettingsScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SettingsScreen, lv_color_hex(0x06534B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingsScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container3 = lv_obj_create(ui_SettingsScreen);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 475);
    lv_obj_set_height(ui_Container3, 479);
    lv_obj_set_x(ui_Container3, -16);
    lv_obj_set_y(ui_Container3, -2);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Slider2 = lv_slider_create(ui_SettingsScreen);
    lv_slider_set_value(ui_Slider2, 30, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider2, 287);
    lv_obj_set_height(ui_Slider2, 63);
    lv_obj_set_x(ui_Slider2, -7);
    lv_obj_set_y(ui_Slider2, 129);
    lv_obj_set_align(ui_Slider2, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0x06A366), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Slider2, lv_color_hex(0x50FC7C), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Slider2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Slider2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Slider2, LV_GRAD_DIR_VER, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Slider2, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Slider2,
                                                                                              lv_obj_get_style_pad_right(ui_Slider2, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Image4 = lv_image_create(ui_SettingsScreen);
    lv_image_set_src(ui_Image4, &ui_img_brightness_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_Image4, -111);
    lv_obj_set_y(ui_Image4, 130);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_upimg = lv_image_create(ui_SettingsScreen);
    lv_image_set_src(ui_upimg, &ui_img_icn_back_png);
    lv_obj_set_width(ui_upimg, 50);
    lv_obj_set_height(ui_upimg, 35);
    lv_obj_set_x(ui_upimg, -12);
    lv_obj_set_y(ui_upimg, 211);
    lv_obj_set_align(ui_upimg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_upimg, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_upimg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_timeoutdropdown = lv_dropdown_create(ui_SettingsScreen);
    lv_dropdown_set_dir(ui_timeoutdropdown, LV_DIR_TOP);
    lv_dropdown_set_options(ui_timeoutdropdown, "03 s\n05 s\n10 s\n20 s\n30 s\nNever");
    lv_obj_set_width(ui_timeoutdropdown, 96);
    lv_obj_set_height(ui_timeoutdropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timeoutdropdown, -169);
    lv_obj_set_y(ui_timeoutdropdown, -179);
    lv_obj_set_align(ui_timeoutdropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_timeoutdropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_timeoutdropdown, lv_color_hex(0xFDF9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_timeoutdropdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_timeoutdropdown, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_timeoutdropdown, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_timeoutdropdown, lv_color_hex(0x0BCBAC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_timeoutdropdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_timeoutdropdown, lv_color_hex(0x0D9A30), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_timeoutdropdown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_timeoutdropdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_timeoutdropdown, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_timeoutdropdown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown2 = lv_dropdown_create(ui_SettingsScreen);
    lv_dropdown_set_dir(ui_Dropdown2, LV_DIR_TOP);
    lv_dropdown_set_options(ui_Dropdown2, "OFF\nLOW\nMED\nHIGH");
    lv_obj_set_width(ui_Dropdown2, 99);
    lv_obj_set_height(ui_Dropdown2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown2, 146);
    lv_obj_set_y(ui_Dropdown2, -180);
    lv_obj_set_align(ui_Dropdown2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_Dropdown2, lv_color_hex(0xFAF9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dropdown2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Dropdown2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Dropdown2, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Dropdown2, lv_color_hex(0x0BCBAC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Dropdown2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Dropdown2, lv_color_hex(0x0D9A30), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Dropdown2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Dropdown2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Dropdown2, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Dropdown2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_SettingsScreen);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -170);
    lv_obj_set_y(ui_Label2, -218);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Timeout");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFDF7F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &ui_font_sans22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_SettingsScreen);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 146);
    lv_obj_set_y(ui_Label4, -219);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Volume");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFDF7F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &ui_font_sans22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_SettingsScreen);
    lv_obj_set_width(ui_Panel1, 78);
    lv_obj_set_height(ui_Panel1, 75);
    lv_obj_set_x(ui_Panel1, -11);
    lv_obj_set_y(ui_Panel1, -194);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x30AD29), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel1, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel1, lv_color_hex(0x06AD63), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Panel1, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image6 = lv_image_create(ui_Panel1);
    lv_image_set_src(ui_Image6, &ui_img_settings_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image6, 0);
    lv_obj_set_y(ui_Image6, 1);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_tempunitswitch = lv_switch_create(ui_SettingsScreen);
    lv_obj_set_width(ui_tempunitswitch, 50);
    lv_obj_set_height(ui_tempunitswitch, 25);
    lv_obj_set_x(ui_tempunitswitch, -206);
    lv_obj_set_y(ui_tempunitswitch, 203);
    lv_obj_set_align(ui_tempunitswitch, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_tempunitswitch, lv_color_hex(0xC8C3C3), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tempunitswitch, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_SettingsScreen);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -163);
    lv_obj_set_y(ui_Label3, 205);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "°F");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xF8F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &ui_font_sans28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image8 = lv_image_create(ui_SettingsScreen);
    lv_image_set_src(ui_Image8, &ui_img_149480563);
    lv_obj_set_width(ui_Image8, 80);
    lv_obj_set_height(ui_Image8, 80);
    lv_obj_set_x(ui_Image8, -16);
    lv_obj_set_y(ui_Image8, -39);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image9 = lv_image_create(ui_SettingsScreen);
    lv_image_set_src(ui_Image9, &ui_img_info_png);
    lv_obj_set_width(ui_Image9, 80);
    lv_obj_set_height(ui_Image9, 80);
    lv_obj_set_x(ui_Image9, 86);
    lv_obj_set_y(ui_Image9, -36);
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_reset = lv_image_create(ui_SettingsScreen);
    lv_image_set_src(ui_reset, &ui_img_undo_png);
    lv_obj_set_width(ui_reset, 80);
    lv_obj_set_height(ui_reset, 80);
    lv_obj_set_x(ui_reset, -118);
    lv_obj_set_y(ui_reset, -35);
    lv_obj_set_align(ui_reset, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_reset, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_reset, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

        ui_Label5 = lv_label_create(ui_SettingsScreen);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -117);
    lv_obj_set_y(ui_Label5, 13);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Reset");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xFAF8F8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &ui_font_sans22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_SettingsScreen);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -15);
    lv_obj_set_y(ui_Label7, 12);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Update");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xFAF8F8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &ui_font_sans22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_SettingsScreen);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 86);
    lv_obj_set_y(ui_Label8, 12);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Info");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xFAF8F8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &ui_font_sans22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_factoryresetcontianer = lv_obj_create(ui_SettingsScreen);
    lv_obj_remove_style_all(ui_factoryresetcontianer);
    lv_obj_set_width(ui_factoryresetcontianer, 441);
    lv_obj_set_height(ui_factoryresetcontianer, 296);
    lv_obj_set_x(ui_factoryresetcontianer, -16);
    lv_obj_set_y(ui_factoryresetcontianer, 21);
    lv_obj_set_align(ui_factoryresetcontianer, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_factoryresetcontianer, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_factoryresetcontianer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_factoryresetcontianer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_factoryresetcontianer, lv_color_hex(0x212020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_factoryresetcontianer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_factoryresetcontianer);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -6);
    lv_obj_set_y(ui_Label6, -116);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Factory Reset");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Label6, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label6, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &ui_font_sans22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_factoryresetcontianer);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 5);
    lv_obj_set_y(ui_Label1, -37);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Restore default configuration and \ndelete saved credentials ?");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Label1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_sans22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_confirmbtn2 = lv_button_create(ui_factoryresetcontianer);
    lv_obj_set_width(ui_confirmbtn2, 116);
    lv_obj_set_height(ui_confirmbtn2, 50);
    lv_obj_set_x(ui_confirmbtn2, 87);
    lv_obj_set_y(ui_confirmbtn2, 31);
    lv_obj_set_align(ui_confirmbtn2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_confirmbtn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_confirmbtn2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_confirmbtn2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_confirmbtn2, lv_color_hex(0xF34C4C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_confirmbtn2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_confirmbtn2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_confirmbtn2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_confirmbtn2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_confirmbtn2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_confirmbtn2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_confirmbtnlbl2 = lv_label_create(ui_confirmbtn2);
    lv_obj_set_width(ui_confirmbtnlbl2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_confirmbtnlbl2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_confirmbtnlbl2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_confirmbtnlbl2, "Confirm");
    lv_obj_set_style_text_color(ui_confirmbtnlbl2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_confirmbtnlbl2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_confirmbtnlbl2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_confirmbtnlbl2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_confirmbtnlbl2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_confirmbtnlbl2, &ui_font_sans22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cancelbtn2 = lv_button_create(ui_factoryresetcontianer);
    lv_obj_set_width(ui_cancelbtn2, 116);
    lv_obj_set_height(ui_cancelbtn2, 50);
    lv_obj_set_x(ui_cancelbtn2, -106);
    lv_obj_set_y(ui_cancelbtn2, 31);
    lv_obj_set_align(ui_cancelbtn2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_cancelbtn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_cancelbtn2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_cancelbtn2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cancelbtn2, lv_color_hex(0xF34C4C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cancelbtn2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cancelbtn2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_cancelbtn2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_cancelbtn2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cancelbtnlbl2 = lv_label_create(ui_cancelbtn2);
    lv_obj_set_width(ui_cancelbtnlbl2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cancelbtnlbl2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_cancelbtnlbl2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cancelbtnlbl2, "Cancel");
    lv_obj_set_style_text_color(ui_cancelbtnlbl2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cancelbtnlbl2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_cancelbtnlbl2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_cancelbtnlbl2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_cancelbtnlbl2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cancelbtnlbl2, &ui_font_sans22, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Slider2, ui_event_Slider2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_upimg, ui_event_upimg, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_timeoutdropdown, ui_event_timeoutdropdown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Dropdown2, ui_event_Dropdown2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_tempunitswitch, ui_event_tempunitswitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image8, ui_event_Image8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_reset, ui_event_reset, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_confirmbtn2, ui_event_confirmbtn2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cancelbtn2, ui_event_cancelbtn2, LV_EVENT_ALL, NULL);

}

void ui_SettingsScreen_screen_destroy(void)
{
    if(ui_SettingsScreen) lv_obj_del(ui_SettingsScreen);

    // NULL screen variables
    ui_SettingsScreen = NULL;
    ui_Container3 = NULL;
    ui_Slider2 = NULL;
    ui_Image4 = NULL;
    ui_upimg = NULL;
    ui_timeoutdropdown = NULL;
    ui_Dropdown2 = NULL;
    ui_Label2 = NULL;
    ui_Label4 = NULL;
    ui_Panel1 = NULL;
    ui_Image6 = NULL;
    ui_tempunitswitch = NULL;
    ui_Label3 = NULL;
    ui_Image8 = NULL;
    ui_Image9 = NULL;
    ui_reset = NULL;
    ui_factoryresetcontianer = NULL;
    ui_Label6 = NULL;
    ui_Label1 = NULL;
    ui_confirmbtn2 = NULL;
    ui_confirmbtnlbl2 = NULL;
    ui_cancelbtn2 = NULL;
    ui_cancelbtnlbl2 = NULL;
    ui_Label5 = NULL;
    ui_Label7 = NULL;
    ui_Label8 = NULL;

}
